/* Generated by Yosys 0.40+50 (git sha1 0f9ee20ea, clang++ 15.0.0 -fPIC -Os) */

(* keep =  1  *)
(* top =  1  *)
(* src = "multiplier_sc.sv:15.1-226.10" *)
module multiplier_sc(clk, a1, a2, b, in_valid);
  (* src = "multiplier_sc.sv:57.1-64.4" *)
  wire _000_;
  (* src = "multiplier_sc.sv:57.1-64.4" *)
  wire _001_;
  (* src = "multiplier_sc.sv:57.1-64.4" *)
  wire _002_;
  (* src = "multiplier_sc.sv:57.1-64.4" *)
  wire _003_;
  (* src = "multiplier_sc.sv:57.1-64.4" *)
  wire _004_;
  (* src = "multiplier_sc.sv:57.1-64.4" *)
  wire _005_;
  (* src = "multiplier_sc.sv:137.21-137.32" *)
  wire [31:0] _006_;
  (* src = "multiplier_sc.sv:139.21-139.32" *)
  wire [31:0] _007_;
  (* src = "multiplier_sc.sv:141.20-141.30" *)
  wire [31:0] _008_;
  (* src = "multiplier_sc.sv:212.18-212.36" *)
  wire _009_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  wire [7:0] _010_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  wire [7:0] _011_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  wire _012_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  wire [3:0] _013_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  wire _014_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  wire [15:0] _015_;
  wire [3:0] _016_;
  wire [15:0] _017_;
  (* src = "multiplier_sc.sv:302.113-302.139" *)
  (* unused_bits = "16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _018_;
  (* src = "multiplier_sc.sv:301.54-301.87" *)
  wire [31:0] _019_;
  (* src = "multiplier_sc.sv:302.97-302.143" *)
  wire [31:0] _020_;
  (* src = "multiplier_sc.sv:302.66-302.144" *)
  wire [31:0] _021_;
  (* src = "multiplier_sc.sv:298.48-298.63" *)
  wire _022_;
  (* src = "multiplier_sc.sv:298.73-298.88" *)
  wire _023_;
  (* src = "multiplier_sc.sv:297.42-297.64" *)
  wire _024_;
  (* src = "multiplier_sc.sv:297.68-297.93" *)
  wire _025_;
  (* src = "multiplier_sc.sv:298.46-298.103" *)
  wire _026_;
  (* src = "multiplier_sc.sv:297.68-297.80" *)
  wire _027_;
  (* src = "multiplier_sc.sv:297.42-297.93" *)
  wire _028_;
  (* src = "multiplier_sc.sv:298.47-298.89" *)
  wire _029_;
  (* src = "multiplier_sc.sv:299.59-299.86" *)
  wire [7:0] _030_;
  (* src = "multiplier_sc.sv:300.59-300.91" *)
  wire [7:0] _031_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  wire [7:0] _032_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  wire [7:0] _033_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  wire _034_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  wire [3:0] _035_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  wire _036_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  wire [15:0] _037_;
  wire [3:0] _038_;
  wire [15:0] _039_;
  (* src = "multiplier_sc.sv:302.113-302.139" *)
  (* unused_bits = "16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _040_;
  (* src = "multiplier_sc.sv:301.54-301.87" *)
  wire [31:0] _041_;
  (* src = "multiplier_sc.sv:302.97-302.143" *)
  wire [31:0] _042_;
  (* src = "multiplier_sc.sv:302.66-302.144" *)
  wire [31:0] _043_;
  (* src = "multiplier_sc.sv:298.48-298.63" *)
  wire _044_;
  (* src = "multiplier_sc.sv:298.73-298.88" *)
  wire _045_;
  (* src = "multiplier_sc.sv:297.42-297.64" *)
  wire _046_;
  (* src = "multiplier_sc.sv:297.68-297.93" *)
  wire _047_;
  (* src = "multiplier_sc.sv:298.46-298.103" *)
  wire _048_;
  (* src = "multiplier_sc.sv:297.68-297.80" *)
  wire _049_;
  (* src = "multiplier_sc.sv:297.42-297.93" *)
  wire _050_;
  (* src = "multiplier_sc.sv:298.47-298.89" *)
  wire _051_;
  (* src = "multiplier_sc.sv:299.59-299.86" *)
  wire [7:0] _052_;
  (* src = "multiplier_sc.sv:300.59-300.91" *)
  wire [7:0] _053_;
  (* src = "multiplier_sc.sv:173.18-173.33" *)
  wire _054_;
  (* src = "multiplier_sc.sv:174.18-174.33" *)
  wire _055_;
  (* src = "multiplier_sc.sv:138.21-138.32" *)
  wire [31:0] _056_;
  (* src = "multiplier_sc.sv:140.23-140.36" *)
  wire [31:0] _057_;
  (* src = "multiplier_sc.sv:142.22-142.34" *)
  wire [31:0] _058_;
  (* src = "multiplier_sc.sv:173.37-173.48" *)
  wire _059_;
  (* src = "multiplier_sc.sv:174.37-174.48" *)
  wire _060_;
  (* src = "multiplier_sc.sv:212.18-212.59" *)
  wire _061_;
  (* src = "multiplier_sc.sv:188.30-188.42" *)
  wire _062_;
  (* src = "multiplier_sc.sv:17.26-17.28" *)
  input [7:0] a1;
  wire [7:0] a1;
  (* src = "multiplier_sc.sv:18.26-18.28" *)
  input [7:0] a2;
  wire [7:0] a2;
  (* src = "multiplier_sc.sv:26.21-26.27" *)
  wire [7:0] a_reg1;
  (* src = "multiplier_sc.sv:26.29-26.40" *)
  wire [7:0] a_reg1_next;
  (* src = "multiplier_sc.sv:26.42-26.48" *)
  wire [7:0] a_reg2;
  (* src = "multiplier_sc.sv:26.50-26.61" *)
  wire [7:0] a_reg2_next;
  (* src = "multiplier_sc.sv:32.5-32.15" *)
  reg a_reg_diff;
  (* src = "multiplier_sc.sv:49.6-49.21" *)
  wire a_reg_next_same;
  (* src = "multiplier_sc.sv:220.6-220.25" *)
  wire assume_1_violate_in;
  (* src = "multiplier_sc.sv:184.5-184.21" *)
  reg assume_2_violate = 1'h0;
  (* src = "multiplier_sc.sv:188.6-188.25" *)
  wire assume_2_violate_in;
  (* src = "multiplier_sc.sv:19.26-19.27" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "multiplier_sc.sv:26.63-26.69" *)
  wire [7:0] b_reg1;
  (* src = "multiplier_sc.sv:26.71-26.82" *)
  wire [7:0] b_reg1_next;
  (* src = "multiplier_sc.sv:26.84-26.90" *)
  wire [7:0] b_reg2;
  (* src = "multiplier_sc.sv:26.92-26.103" *)
  wire [7:0] b_reg2_next;
  (* src = "multiplier_sc.sv:32.17-32.27" *)
  reg b_reg_diff;
  (* src = "multiplier_sc.sv:50.6-50.21" *)
  wire b_reg_next_same;
  (* src = "multiplier_sc.sv:25.6-25.11" *)
  wire busy1;
  (* src = "multiplier_sc.sv:25.13-25.23" *)
  wire busy1_next;
  (* src = "multiplier_sc.sv:25.25-25.30" *)
  (* unused_bits = "0" *)
  wire busy2;
  (* src = "multiplier_sc.sv:25.32-25.42" *)
  wire busy2_next;
  (* src = "multiplier_sc.sv:32.55-32.64" *)
  reg busy_diff;
  (* src = "multiplier_sc.sv:53.6-53.20" *)
  wire busy_next_same;
  (* src = "multiplier_sc.sv:16.11-16.14" *)
  input clk;
  wire clk;
  (* hdlname = "copy1 a" *)
  (* src = "multiplier_sc.sv:233.26-233.27" *)
  wire [7:0] \copy1.a ;
  (* hdlname = "copy1 a_reg" *)
  (* src = "multiplier_sc.sv:240.27-240.32" *)
  reg [7:0] \copy1.a_reg  = 8'h00;
  (* hdlname = "copy1 a_reg_next" *)
  (* src = "multiplier_sc.sv:245.27-245.37" *)
  wire [7:0] \copy1.a_reg_next ;
  (* hdlname = "copy1 a_reg_next_same" *)
  (* src = "multiplier_sc.sv:256.11-256.26" *)
  wire \copy1.a_reg_next_same ;
  (* hdlname = "copy1 a_reg_other" *)
  (* src = "multiplier_sc.sv:262.26-262.37" *)
  wire [7:0] \copy1.a_reg_other ;
  (* hdlname = "copy1 a_reg_other_next" *)
  (* src = "multiplier_sc.sv:268.26-268.42" *)
  wire [7:0] \copy1.a_reg_other_next ;
  (* hdlname = "copy1 a_reg_same" *)
  (* src = "multiplier_sc.sv:250.11-250.21" *)
  wire \copy1.a_reg_same ;
  (* hdlname = "copy1 a_reg_this" *)
  (* src = "multiplier_sc.sv:292.25-292.35" *)
  wire [7:0] \copy1.a_reg_this ;
  (* hdlname = "copy1 b" *)
  (* src = "multiplier_sc.sv:234.26-234.27" *)
  wire [7:0] \copy1.b ;
  (* hdlname = "copy1 b_reg" *)
  (* src = "multiplier_sc.sv:241.27-241.32" *)
  reg [7:0] \copy1.b_reg  = 8'h00;
  (* hdlname = "copy1 b_reg_next" *)
  (* src = "multiplier_sc.sv:246.27-246.37" *)
  wire [7:0] \copy1.b_reg_next ;
  (* hdlname = "copy1 b_reg_next_same" *)
  (* src = "multiplier_sc.sv:257.11-257.26" *)
  wire \copy1.b_reg_next_same ;
  (* hdlname = "copy1 b_reg_other" *)
  (* src = "multiplier_sc.sv:263.26-263.37" *)
  wire [7:0] \copy1.b_reg_other ;
  (* hdlname = "copy1 b_reg_other_next" *)
  (* src = "multiplier_sc.sv:269.26-269.42" *)
  wire [7:0] \copy1.b_reg_other_next ;
  (* hdlname = "copy1 b_reg_same" *)
  (* src = "multiplier_sc.sv:251.11-251.21" *)
  wire \copy1.b_reg_same ;
  (* hdlname = "copy1 b_reg_this" *)
  (* src = "multiplier_sc.sv:293.25-293.35" *)
  wire [7:0] \copy1.b_reg_this ;
  (* hdlname = "copy1 busy" *)
  (* src = "multiplier_sc.sv:238.12-238.16" *)
  reg \copy1.busy  = 1'h0;
  (* hdlname = "copy1 busy_next" *)
  (* src = "multiplier_sc.sv:243.12-243.21" *)
  wire \copy1.busy_next ;
  (* hdlname = "copy1 busy_next_same" *)
  (* src = "multiplier_sc.sv:260.11-260.25" *)
  wire \copy1.busy_next_same ;
  (* hdlname = "copy1 busy_other" *)
  (* src = "multiplier_sc.sv:266.11-266.21" *)
  wire \copy1.busy_other ;
  (* hdlname = "copy1 busy_other_next" *)
  (* src = "multiplier_sc.sv:272.11-272.26" *)
  wire \copy1.busy_other_next ;
  (* hdlname = "copy1 busy_same" *)
  (* src = "multiplier_sc.sv:254.11-254.20" *)
  wire \copy1.busy_same ;
  (* hdlname = "copy1 busy_this" *)
  (* src = "multiplier_sc.sv:290.10-290.19" *)
  wire \copy1.busy_this ;
  (* hdlname = "copy1 clk" *)
  (* src = "multiplier_sc.sv:231.11-231.14" *)
  wire \copy1.clk ;
  (* hdlname = "copy1 counter" *)
  (* src = "multiplier_sc.sv:242.18-242.25" *)
  reg [3:0] \copy1.counter ;
  (* hdlname = "copy1 counter_next" *)
  (* src = "multiplier_sc.sv:248.18-248.30" *)
  wire [3:0] \copy1.counter_next ;
  (* hdlname = "copy1 counter_next_same" *)
  (* src = "multiplier_sc.sv:259.11-259.28" *)
  wire \copy1.counter_next_same ;
  (* hdlname = "copy1 counter_other" *)
  (* src = "multiplier_sc.sv:265.17-265.30" *)
  wire [3:0] \copy1.counter_other ;
  (* hdlname = "copy1 counter_other_next" *)
  (* src = "multiplier_sc.sv:271.17-271.35" *)
  wire [3:0] \copy1.counter_other_next ;
  (* hdlname = "copy1 counter_same" *)
  (* src = "multiplier_sc.sv:253.11-253.23" *)
  wire \copy1.counter_same ;
  (* hdlname = "copy1 counter_this" *)
  (* src = "multiplier_sc.sv:294.16-294.28" *)
  wire [3:0] \copy1.counter_this ;
  (* hdlname = "copy1 finish" *)
  (* src = "multiplier_sc.sv:239.12-239.18" *)
  reg \copy1.finish  = 1'h0;
  (* hdlname = "copy1 finish_next" *)
  (* src = "multiplier_sc.sv:244.12-244.23" *)
  wire \copy1.finish_next ;
  (* hdlname = "copy1 finish_next_same" *)
  (* src = "multiplier_sc.sv:261.11-261.27" *)
  wire \copy1.finish_next_same ;
  (* hdlname = "copy1 finish_other" *)
  (* src = "multiplier_sc.sv:267.11-267.23" *)
  wire \copy1.finish_other ;
  (* hdlname = "copy1 finish_other_next" *)
  (* src = "multiplier_sc.sv:273.11-273.28" *)
  wire \copy1.finish_other_next ;
  (* hdlname = "copy1 finish_same" *)
  (* src = "multiplier_sc.sv:255.11-255.22" *)
  wire \copy1.finish_same ;
  (* hdlname = "copy1 finish_this" *)
  (* src = "multiplier_sc.sv:291.10-291.21" *)
  wire \copy1.finish_this ;
  (* hdlname = "copy1 in_ready" *)
  (* src = "multiplier_sc.sv:237.12-237.20" *)
  wire \copy1.in_ready ;
  (* hdlname = "copy1 in_valid" *)
  (* src = "multiplier_sc.sv:232.11-232.19" *)
  wire \copy1.in_valid ;
  (* hdlname = "copy1 o" *)
  (* src = "multiplier_sc.sv:235.34-235.35" *)
  wire [15:0] \copy1.o ;
  (* hdlname = "copy1 o_reg" *)
  (* src = "multiplier_sc.sv:277.31-277.36" *)
  reg [15:0] \copy1.o_reg  = 16'h0000;
  (* hdlname = "copy1 o_reg_next" *)
  (* src = "multiplier_sc.sv:247.34-247.44" *)
  wire [15:0] \copy1.o_reg_next ;
  (* hdlname = "copy1 o_reg_next_same" *)
  (* src = "multiplier_sc.sv:258.11-258.26" *)
  wire \copy1.o_reg_next_same ;
  (* hdlname = "copy1 o_reg_other" *)
  (* src = "multiplier_sc.sv:264.33-264.44" *)
  wire [15:0] \copy1.o_reg_other ;
  (* hdlname = "copy1 o_reg_other_next" *)
  (* src = "multiplier_sc.sv:270.33-270.49" *)
  wire [15:0] \copy1.o_reg_other_next ;
  (* hdlname = "copy1 o_reg_same" *)
  (* src = "multiplier_sc.sv:252.11-252.21" *)
  wire \copy1.o_reg_same ;
  (* hdlname = "copy1 o_reg_this" *)
  (* src = "multiplier_sc.sv:295.32-295.42" *)
  wire [15:0] \copy1.o_reg_this ;
  (* hdlname = "copy1 out_valid" *)
  (* src = "multiplier_sc.sv:236.12-236.21" *)
  wire \copy1.out_valid ;
  (* hdlname = "copy1 pause" *)
  (* src = "multiplier_sc.sv:274.11-274.16" *)
  wire \copy1.pause ;
  (* hdlname = "copy2 a" *)
  (* src = "multiplier_sc.sv:233.26-233.27" *)
  wire [7:0] \copy2.a ;
  (* hdlname = "copy2 a_reg" *)
  (* src = "multiplier_sc.sv:240.27-240.32" *)
  reg [7:0] \copy2.a_reg  = 8'h00;
  (* hdlname = "copy2 a_reg_next" *)
  (* src = "multiplier_sc.sv:245.27-245.37" *)
  wire [7:0] \copy2.a_reg_next ;
  (* hdlname = "copy2 a_reg_next_same" *)
  (* src = "multiplier_sc.sv:256.11-256.26" *)
  wire \copy2.a_reg_next_same ;
  (* hdlname = "copy2 a_reg_other" *)
  (* src = "multiplier_sc.sv:262.26-262.37" *)
  wire [7:0] \copy2.a_reg_other ;
  (* hdlname = "copy2 a_reg_other_next" *)
  (* src = "multiplier_sc.sv:268.26-268.42" *)
  wire [7:0] \copy2.a_reg_other_next ;
  (* hdlname = "copy2 a_reg_same" *)
  (* src = "multiplier_sc.sv:250.11-250.21" *)
  wire \copy2.a_reg_same ;
  (* hdlname = "copy2 a_reg_this" *)
  (* src = "multiplier_sc.sv:292.25-292.35" *)
  wire [7:0] \copy2.a_reg_this ;
  (* hdlname = "copy2 b" *)
  (* src = "multiplier_sc.sv:234.26-234.27" *)
  wire [7:0] \copy2.b ;
  (* hdlname = "copy2 b_reg" *)
  (* src = "multiplier_sc.sv:241.27-241.32" *)
  reg [7:0] \copy2.b_reg  = 8'h00;
  (* hdlname = "copy2 b_reg_next" *)
  (* src = "multiplier_sc.sv:246.27-246.37" *)
  wire [7:0] \copy2.b_reg_next ;
  (* hdlname = "copy2 b_reg_next_same" *)
  (* src = "multiplier_sc.sv:257.11-257.26" *)
  wire \copy2.b_reg_next_same ;
  (* hdlname = "copy2 b_reg_other" *)
  (* src = "multiplier_sc.sv:263.26-263.37" *)
  wire [7:0] \copy2.b_reg_other ;
  (* hdlname = "copy2 b_reg_other_next" *)
  (* src = "multiplier_sc.sv:269.26-269.42" *)
  wire [7:0] \copy2.b_reg_other_next ;
  (* hdlname = "copy2 b_reg_same" *)
  (* src = "multiplier_sc.sv:251.11-251.21" *)
  wire \copy2.b_reg_same ;
  (* hdlname = "copy2 b_reg_this" *)
  (* src = "multiplier_sc.sv:293.25-293.35" *)
  wire [7:0] \copy2.b_reg_this ;
  (* hdlname = "copy2 busy" *)
  (* src = "multiplier_sc.sv:238.12-238.16" *)
  reg \copy2.busy  = 1'h0;
  (* hdlname = "copy2 busy_next" *)
  (* src = "multiplier_sc.sv:243.12-243.21" *)
  wire \copy2.busy_next ;
  (* hdlname = "copy2 busy_next_same" *)
  (* src = "multiplier_sc.sv:260.11-260.25" *)
  wire \copy2.busy_next_same ;
  (* hdlname = "copy2 busy_other" *)
  (* src = "multiplier_sc.sv:266.11-266.21" *)
  wire \copy2.busy_other ;
  (* hdlname = "copy2 busy_other_next" *)
  (* src = "multiplier_sc.sv:272.11-272.26" *)
  wire \copy2.busy_other_next ;
  (* hdlname = "copy2 busy_same" *)
  (* src = "multiplier_sc.sv:254.11-254.20" *)
  wire \copy2.busy_same ;
  (* hdlname = "copy2 busy_this" *)
  (* src = "multiplier_sc.sv:290.10-290.19" *)
  wire \copy2.busy_this ;
  (* hdlname = "copy2 clk" *)
  (* src = "multiplier_sc.sv:231.11-231.14" *)
  wire \copy2.clk ;
  (* hdlname = "copy2 counter" *)
  (* src = "multiplier_sc.sv:242.18-242.25" *)
  reg [3:0] \copy2.counter ;
  (* hdlname = "copy2 counter_next" *)
  (* src = "multiplier_sc.sv:248.18-248.30" *)
  wire [3:0] \copy2.counter_next ;
  (* hdlname = "copy2 counter_next_same" *)
  (* src = "multiplier_sc.sv:259.11-259.28" *)
  wire \copy2.counter_next_same ;
  (* hdlname = "copy2 counter_other" *)
  (* src = "multiplier_sc.sv:265.17-265.30" *)
  wire [3:0] \copy2.counter_other ;
  (* hdlname = "copy2 counter_other_next" *)
  (* src = "multiplier_sc.sv:271.17-271.35" *)
  wire [3:0] \copy2.counter_other_next ;
  (* hdlname = "copy2 counter_same" *)
  (* src = "multiplier_sc.sv:253.11-253.23" *)
  wire \copy2.counter_same ;
  (* hdlname = "copy2 counter_this" *)
  (* src = "multiplier_sc.sv:294.16-294.28" *)
  wire [3:0] \copy2.counter_this ;
  (* hdlname = "copy2 finish" *)
  (* src = "multiplier_sc.sv:239.12-239.18" *)
  reg \copy2.finish  = 1'h0;
  (* hdlname = "copy2 finish_next" *)
  (* src = "multiplier_sc.sv:244.12-244.23" *)
  wire \copy2.finish_next ;
  (* hdlname = "copy2 finish_next_same" *)
  (* src = "multiplier_sc.sv:261.11-261.27" *)
  wire \copy2.finish_next_same ;
  (* hdlname = "copy2 finish_other" *)
  (* src = "multiplier_sc.sv:267.11-267.23" *)
  wire \copy2.finish_other ;
  (* hdlname = "copy2 finish_other_next" *)
  (* src = "multiplier_sc.sv:273.11-273.28" *)
  wire \copy2.finish_other_next ;
  (* hdlname = "copy2 finish_same" *)
  (* src = "multiplier_sc.sv:255.11-255.22" *)
  wire \copy2.finish_same ;
  (* hdlname = "copy2 finish_this" *)
  (* src = "multiplier_sc.sv:291.10-291.21" *)
  wire \copy2.finish_this ;
  (* hdlname = "copy2 in_ready" *)
  (* src = "multiplier_sc.sv:237.12-237.20" *)
  wire \copy2.in_ready ;
  (* hdlname = "copy2 in_valid" *)
  (* src = "multiplier_sc.sv:232.11-232.19" *)
  wire \copy2.in_valid ;
  (* hdlname = "copy2 o" *)
  (* src = "multiplier_sc.sv:235.34-235.35" *)
  wire [15:0] \copy2.o ;
  (* hdlname = "copy2 o_reg" *)
  (* src = "multiplier_sc.sv:277.31-277.36" *)
  reg [15:0] \copy2.o_reg  = 16'h0000;
  (* hdlname = "copy2 o_reg_next" *)
  (* src = "multiplier_sc.sv:247.34-247.44" *)
  wire [15:0] \copy2.o_reg_next ;
  (* hdlname = "copy2 o_reg_next_same" *)
  (* src = "multiplier_sc.sv:258.11-258.26" *)
  wire \copy2.o_reg_next_same ;
  (* hdlname = "copy2 o_reg_other" *)
  (* src = "multiplier_sc.sv:264.33-264.44" *)
  wire [15:0] \copy2.o_reg_other ;
  (* hdlname = "copy2 o_reg_other_next" *)
  (* src = "multiplier_sc.sv:270.33-270.49" *)
  wire [15:0] \copy2.o_reg_other_next ;
  (* hdlname = "copy2 o_reg_same" *)
  (* src = "multiplier_sc.sv:252.11-252.21" *)
  wire \copy2.o_reg_same ;
  (* hdlname = "copy2 o_reg_this" *)
  (* src = "multiplier_sc.sv:295.32-295.42" *)
  wire [15:0] \copy2.o_reg_this ;
  (* hdlname = "copy2 out_valid" *)
  (* src = "multiplier_sc.sv:236.12-236.21" *)
  wire \copy2.out_valid ;
  (* hdlname = "copy2 pause" *)
  (* src = "multiplier_sc.sv:274.11-274.16" *)
  wire \copy2.pause ;
  (* src = "multiplier_sc.sv:27.12-27.20" *)
  wire [3:0] counter1;
  (* src = "multiplier_sc.sv:27.22-27.35" *)
  wire [3:0] counter1_next;
  (* src = "multiplier_sc.sv:27.37-27.45" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] counter2;
  (* src = "multiplier_sc.sv:27.47-27.60" *)
  wire [3:0] counter2_next;
  (* src = "multiplier_sc.sv:32.41-32.53" *)
  reg counter_diff;
  (* src = "multiplier_sc.sv:52.6-52.23" *)
  wire counter_next_same;
  (* src = "multiplier_sc.sv:25.44-25.51" *)
  wire finish1;
  (* src = "multiplier_sc.sv:25.53-25.65" *)
  wire finish1_next;
  (* src = "multiplier_sc.sv:25.67-25.74" *)
  wire finish2;
  (* src = "multiplier_sc.sv:25.76-25.88" *)
  wire finish2_next;
  (* src = "multiplier_sc.sv:32.66-32.77" *)
  reg finish_diff;
  (* src = "multiplier_sc.sv:54.6-54.22" *)
  wire finish_next_same;
  (* src = "multiplier_sc.sv:20.11-20.19" *)
  input in_valid;
  wire in_valid;
  (* src = "multiplier_sc.sv:23.28-23.30" *)
  wire [15:0] o1;
  (* src = "multiplier_sc.sv:23.32-23.39" *)
  wire [15:0] o1_next;
  (* src = "multiplier_sc.sv:23.41-23.43" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [15:0] o2;
  (* src = "multiplier_sc.sv:23.45-23.52" *)
  wire [15:0] o2_next;
  (* src = "multiplier_sc.sv:32.29-32.39" *)
  reg o_reg_diff;
  (* src = "multiplier_sc.sv:51.6-51.21" *)
  wire o_reg_next_same;
  (* src = "multiplier_sc.sv:24.6-24.16" *)
  wire out_valid1;
  (* src = "multiplier_sc.sv:24.18-24.28" *)
  wire out_valid2;
  (* src = "multiplier_sc.sv:165.6-165.13" *)
  wire pause_1;
  (* src = "multiplier_sc.sv:165.15-165.22" *)
  wire pause_2;
  (* src = "multiplier_sc.sv:189.28-189.32" *)
  wire [15:0] res1;
  (* src = "multiplier_sc.sv:190.28-190.32" *)
  wire [15:0] res2;
  always @* if (1'h1) assert(_061_);
  assign _009_ = finish1 == (* src = "multiplier_sc.sv:212.18-212.36" *) finish2;
  assign _016_ = \copy1.counter_this  + (* src = "multiplier_sc.sv:301.71-301.87" *) 1'h1;
  assign _017_ = \copy1.o_reg_this  + (* src = "multiplier_sc.sv:302.83-302.144" *) _020_[15:0];
  assign _022_ = ! (* src = "multiplier_sc.sv:298.48-298.63" *) \copy1.a_reg_this ;
  assign _023_ = ! (* src = "multiplier_sc.sv:298.73-298.88" *) \copy1.b_reg_this ;
  assign _024_ = \copy1.in_valid  && (* src = "multiplier_sc.sv:297.42-297.64" *) \copy1.in_ready ;
  assign _025_ = _027_ && (* src = "multiplier_sc.sv:297.68-297.93" *) \copy1.busy_this ;
  assign _026_ = _029_ && (* src = "multiplier_sc.sv:298.46-298.103" *) \copy1.busy_this ;
  assign \copy1.in_ready  = ! (* src = "multiplier_sc.sv:297.54-297.64" *) \copy1.busy_this ;
  assign _027_ = ! (* src = "multiplier_sc.sv:297.68-297.80" *) \copy1.finish_next ;
  assign _028_ = _024_ || (* src = "multiplier_sc.sv:297.42-297.93" *) _025_;
  assign _029_ = _022_ || (* src = "multiplier_sc.sv:298.47-298.89" *) _023_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  always @(posedge \copy1.clk )
    \copy1.a_reg  <= _010_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  always @(posedge \copy1.clk )
    \copy1.b_reg  <= _011_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  always @(posedge \copy1.clk )
    \copy1.counter  <= _013_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  always @(posedge \copy1.clk )
    \copy1.busy  <= _012_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  always @(posedge \copy1.clk )
    \copy1.finish  <= _014_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  always @(posedge \copy1.clk )
    \copy1.o_reg  <= _015_;
  assign _018_[15:0] = \copy1.a_reg_this  << (* src = "multiplier_sc.sv:302.113-302.139" *) \copy1.counter_this ;
  assign \copy1.busy_this  = \copy1.busy_same  ? (* src = "multiplier_sc.sv:290.22-290.51" *) \copy1.busy_other  : \copy1.busy ;
  assign \copy1.finish_this  = \copy1.finish_same  ? (* src = "multiplier_sc.sv:291.24-291.59" *) \copy1.finish_other  : \copy1.finish ;
  assign \copy1.a_reg_this  = \copy1.a_reg_same  ? (* src = "multiplier_sc.sv:292.38-292.70" *) \copy1.a_reg_other  : \copy1.a_reg ;
  assign \copy1.b_reg_this  = \copy1.b_reg_same  ? (* src = "multiplier_sc.sv:293.38-293.70" *) \copy1.b_reg_other  : \copy1.b_reg ;
  assign \copy1.counter_this  = \copy1.counter_same  ? (* src = "multiplier_sc.sv:294.31-294.69" *) \copy1.counter_other  : \copy1.counter ;
  assign \copy1.o_reg_this  = \copy1.o_reg_same  ? (* src = "multiplier_sc.sv:295.45-295.77" *) \copy1.o_reg_other  : \copy1.o_reg ;
  assign \copy1.busy_next  = \copy1.pause  ? (* src = "multiplier_sc.sv:297.22-297.93" *) \copy1.busy_this  : _028_;
  assign \copy1.finish_next  = \copy1.pause  ? (* src = "multiplier_sc.sv:298.24-298.103" *) \copy1.finish_this  : _026_;
  assign _030_ = \copy1.busy_this  ? (* src = "multiplier_sc.sv:299.59-299.86" *) \copy1.a_reg_this  : \copy1.a ;
  assign \copy1.a_reg_next  = \copy1.pause  ? (* src = "multiplier_sc.sv:299.38-299.86" *) \copy1.a_reg_this  : _030_;
  assign _031_ = \copy1.busy_this  ? (* src = "multiplier_sc.sv:300.59-300.91" *) { 1'h0, \copy1.b_reg_this [7:1] } : \copy1.b ;
  assign \copy1.b_reg_next  = \copy1.pause  ? (* src = "multiplier_sc.sv:300.38-300.91" *) \copy1.b_reg_this  : _031_;
  assign _019_[3:0] = \copy1.busy_this  ? (* src = "multiplier_sc.sv:301.54-301.87" *) _016_ : 4'h0;
  assign \copy1.counter_next  = \copy1.pause  ? (* src = "multiplier_sc.sv:301.31-301.87" *) \copy1.counter_this  : _019_[3:0];
  assign _020_[15:0] = \copy1.b_reg_this [0] ? (* src = "multiplier_sc.sv:302.97-302.143" *) _018_[15:0] : 16'h0000;
  assign _021_[15:0] = \copy1.busy_this  ? (* src = "multiplier_sc.sv:302.66-302.144" *) _017_ : 16'h0000;
  assign \copy1.o_reg_next  = \copy1.pause  ? (* src = "multiplier_sc.sv:302.45-302.144" *) \copy1.o_reg_this  : _021_[15:0];
  assign _014_ = \copy1.finish_next_same  ? (* src = "multiplier_sc.sv:307.19-307.69" *) \copy1.finish_other_next  : \copy1.finish_next ;
  assign _012_ = \copy1.busy_next_same  ? (* src = "multiplier_sc.sv:308.17-308.61" *) \copy1.busy_other_next  : \copy1.busy_next ;
  assign _010_ = \copy1.a_reg_next_same  ? (* src = "multiplier_sc.sv:309.18-309.65" *) \copy1.a_reg_other_next  : \copy1.a_reg_next ;
  assign _011_ = \copy1.b_reg_next_same  ? (* src = "multiplier_sc.sv:310.18-310.65" *) \copy1.b_reg_other_next  : \copy1.b_reg_next ;
  assign _013_ = \copy1.counter_next_same  ? (* src = "multiplier_sc.sv:311.20-311.73" *) \copy1.counter_other_next  : \copy1.counter_next ;
  assign _015_ = \copy1.o_reg_next_same  ? (* src = "multiplier_sc.sv:312.18-312.65" *) \copy1.o_reg_other_next  : \copy1.o_reg_next ;
  assign _038_ = \copy2.counter_this  + (* src = "multiplier_sc.sv:301.71-301.87" *) 1'h1;
  assign _039_ = \copy2.o_reg_this  + (* src = "multiplier_sc.sv:302.83-302.144" *) _042_[15:0];
  assign _044_ = ! (* src = "multiplier_sc.sv:298.48-298.63" *) \copy2.a_reg_this ;
  assign _045_ = ! (* src = "multiplier_sc.sv:298.73-298.88" *) \copy2.b_reg_this ;
  assign _046_ = \copy2.in_valid  && (* src = "multiplier_sc.sv:297.42-297.64" *) \copy2.in_ready ;
  assign _047_ = _049_ && (* src = "multiplier_sc.sv:297.68-297.93" *) \copy2.busy_this ;
  assign _048_ = _051_ && (* src = "multiplier_sc.sv:298.46-298.103" *) \copy2.busy_this ;
  assign \copy2.in_ready  = ! (* src = "multiplier_sc.sv:297.54-297.64" *) \copy2.busy_this ;
  assign _049_ = ! (* src = "multiplier_sc.sv:297.68-297.80" *) \copy2.finish_next ;
  assign _050_ = _046_ || (* src = "multiplier_sc.sv:297.42-297.93" *) _047_;
  assign _051_ = _044_ || (* src = "multiplier_sc.sv:298.47-298.89" *) _045_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  always @(posedge \copy2.clk )
    \copy2.a_reg  <= _032_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  always @(posedge \copy2.clk )
    \copy2.b_reg  <= _033_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  always @(posedge \copy2.clk )
    \copy2.counter  <= _035_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  always @(posedge \copy2.clk )
    \copy2.busy  <= _034_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  always @(posedge \copy2.clk )
    \copy2.finish  <= _036_;
  (* src = "multiplier_sc.sv:306.5-313.8" *)
  always @(posedge \copy2.clk )
    \copy2.o_reg  <= _037_;
  assign _040_[15:0] = \copy2.a_reg_this  << (* src = "multiplier_sc.sv:302.113-302.139" *) \copy2.counter_this ;
  assign \copy2.busy_this  = \copy2.busy_same  ? (* src = "multiplier_sc.sv:290.22-290.51" *) \copy2.busy_other  : \copy2.busy ;
  assign \copy2.finish_this  = \copy2.finish_same  ? (* src = "multiplier_sc.sv:291.24-291.59" *) \copy2.finish_other  : \copy2.finish ;
  assign \copy2.a_reg_this  = \copy2.a_reg_same  ? (* src = "multiplier_sc.sv:292.38-292.70" *) \copy2.a_reg_other  : \copy2.a_reg ;
  assign \copy2.b_reg_this  = \copy2.b_reg_same  ? (* src = "multiplier_sc.sv:293.38-293.70" *) \copy2.b_reg_other  : \copy2.b_reg ;
  assign \copy2.counter_this  = \copy2.counter_same  ? (* src = "multiplier_sc.sv:294.31-294.69" *) \copy2.counter_other  : \copy2.counter ;
  assign \copy2.o_reg_this  = \copy2.o_reg_same  ? (* src = "multiplier_sc.sv:295.45-295.77" *) \copy2.o_reg_other  : \copy2.o_reg ;
  assign \copy2.busy_next  = \copy2.pause  ? (* src = "multiplier_sc.sv:297.22-297.93" *) \copy2.busy_this  : _050_;
  assign \copy2.finish_next  = \copy2.pause  ? (* src = "multiplier_sc.sv:298.24-298.103" *) \copy2.finish_this  : _048_;
  assign _052_ = \copy2.busy_this  ? (* src = "multiplier_sc.sv:299.59-299.86" *) \copy2.a_reg_this  : \copy2.a ;
  assign \copy2.a_reg_next  = \copy2.pause  ? (* src = "multiplier_sc.sv:299.38-299.86" *) \copy2.a_reg_this  : _052_;
  assign _053_ = \copy2.busy_this  ? (* src = "multiplier_sc.sv:300.59-300.91" *) { 1'h0, \copy2.b_reg_this [7:1] } : \copy2.b ;
  assign \copy2.b_reg_next  = \copy2.pause  ? (* src = "multiplier_sc.sv:300.38-300.91" *) \copy2.b_reg_this  : _053_;
  assign _041_[3:0] = \copy2.busy_this  ? (* src = "multiplier_sc.sv:301.54-301.87" *) _038_ : 4'h0;
  assign \copy2.counter_next  = \copy2.pause  ? (* src = "multiplier_sc.sv:301.31-301.87" *) \copy2.counter_this  : _041_[3:0];
  assign _042_[15:0] = \copy2.b_reg_this [0] ? (* src = "multiplier_sc.sv:302.97-302.143" *) _040_[15:0] : 16'h0000;
  assign _043_[15:0] = \copy2.busy_this  ? (* src = "multiplier_sc.sv:302.66-302.144" *) _039_ : 16'h0000;
  assign \copy2.o_reg_next  = \copy2.pause  ? (* src = "multiplier_sc.sv:302.45-302.144" *) \copy2.o_reg_this  : _043_[15:0];
  assign _036_ = \copy2.finish_next_same  ? (* src = "multiplier_sc.sv:307.19-307.69" *) \copy2.finish_other_next  : \copy2.finish_next ;
  assign _034_ = \copy2.busy_next_same  ? (* src = "multiplier_sc.sv:308.17-308.61" *) \copy2.busy_other_next  : \copy2.busy_next ;
  assign _032_ = \copy2.a_reg_next_same  ? (* src = "multiplier_sc.sv:309.18-309.65" *) \copy2.a_reg_other_next  : \copy2.a_reg_next ;
  assign _033_ = \copy2.b_reg_next_same  ? (* src = "multiplier_sc.sv:310.18-310.65" *) \copy2.b_reg_other_next  : \copy2.b_reg_next ;
  assign _035_ = \copy2.counter_next_same  ? (* src = "multiplier_sc.sv:311.20-311.73" *) \copy2.counter_other_next  : \copy2.counter_next ;
  assign _037_ = \copy2.o_reg_next_same  ? (* src = "multiplier_sc.sv:312.18-312.65" *) \copy2.o_reg_other_next  : \copy2.o_reg_next ;
  assign _054_ = $signed(32'd1) && (* src = "multiplier_sc.sv:173.18-173.33" *) out_valid1;
  assign pause_1 = _054_ && (* src = "multiplier_sc.sv:173.18-173.48" *) _059_;
  assign _055_ = $signed(32'd1) && (* src = "multiplier_sc.sv:174.18-174.33" *) out_valid2;
  assign pause_2 = _055_ && (* src = "multiplier_sc.sv:174.18-174.48" *) _060_;
  assign _006_[0] = ! (* src = "multiplier_sc.sv:137.21-137.32" *) a_reg_diff;
  assign _056_[0] = ! (* src = "multiplier_sc.sv:138.21-138.32" *) b_reg_diff;
  assign _007_[0] = ! (* src = "multiplier_sc.sv:139.21-139.32" *) o_reg_diff;
  assign _057_[0] = ! (* src = "multiplier_sc.sv:140.23-140.36" *) counter_diff;
  assign _008_[0] = ! (* src = "multiplier_sc.sv:141.20-141.30" *) busy_diff;
  assign _058_[0] = ! (* src = "multiplier_sc.sv:142.22-142.34" *) finish_diff;
  assign _059_ = ! (* src = "multiplier_sc.sv:173.37-173.48" *) out_valid2;
  assign _060_ = ! (* src = "multiplier_sc.sv:174.37-174.48" *) out_valid1;
  assign assume_2_violate_in = _062_ || (* src = "multiplier_sc.sv:188.28-188.64" *) assume_2_violate;
  assign _061_ = _009_ || (* src = "multiplier_sc.sv:212.18-212.59" *) assume_2_violate_in;
  assign res1 = a_reg1 * (* src = "multiplier_sc.sv:189.35-189.50" *) b_reg1;
  assign res2 = a_reg2 * (* src = "multiplier_sc.sv:190.35-190.50" *) b_reg2;
  assign _062_ = res1 != (* src = "multiplier_sc.sv:188.30-188.42" *) res2;
  assign _000_ = a_reg1_next != (* src = "multiplier_sc.sv:58.19-58.45" *) a_reg2_next;
  assign _001_ = b_reg1_next != (* src = "multiplier_sc.sv:59.19-59.45" *) b_reg2_next;
  assign _005_ = o1_next != (* src = "multiplier_sc.sv:60.19-60.37" *) o2_next;
  assign _003_ = counter1_next != (* src = "multiplier_sc.sv:61.21-61.51" *) counter2_next;
  assign _002_ = busy1_next != (* src = "multiplier_sc.sv:62.18-62.42" *) busy2_next;
  assign _004_ = finish1_next != (* src = "multiplier_sc.sv:63.20-63.48" *) finish2_next;
  (* src = "multiplier_sc.sv:185.1-187.4" *)
  always @(posedge clk)
    assume_2_violate <= assume_2_violate_in;
  (* src = "multiplier_sc.sv:57.1-64.4" *)
  always @(posedge clk)
    a_reg_diff <= _000_;
  (* src = "multiplier_sc.sv:57.1-64.4" *)
  always @(posedge clk)
    b_reg_diff <= _001_;
  (* src = "multiplier_sc.sv:57.1-64.4" *)
  always @(posedge clk)
    o_reg_diff <= _005_;
  (* src = "multiplier_sc.sv:57.1-64.4" *)
  always @(posedge clk)
    counter_diff <= _003_;
  (* src = "multiplier_sc.sv:57.1-64.4" *)
  always @(posedge clk)
    busy_diff <= _002_;
  (* src = "multiplier_sc.sv:57.1-64.4" *)
  always @(posedge clk)
    finish_diff <= _004_;
  assign _006_[31:1] = 31'h00000000;
  assign _007_[31:1] = 31'h00000000;
  assign _008_[31:1] = 31'h00000000;
  assign _056_[31:1] = 31'h00000000;
  assign _057_[31:1] = 31'h00000000;
  assign _058_[31:1] = 31'h00000000;
  assign a_reg_next_same = 1'h0;
  assign assume_1_violate_in = 1'h0;
  assign b_reg_next_same = 1'h0;
  assign busy_next_same = 1'h0;
  assign counter_next_same = 1'h0;
  assign finish_next_same = 1'h0;
  assign o_reg_next_same = 1'h0;
  assign _041_[31:4] = 28'b000000000000000000000000000x;
  assign _042_[31:16] = 16'hxxxx;
  assign _043_[31:16] = 16'hxxxx;
  assign \copy2.o  = \copy2.o_reg_this ;
  assign \copy2.out_valid  = \copy2.finish_this ;
  assign \copy2.a  = a2;
  assign a_reg2 = \copy2.a_reg ;
  assign a_reg2_next = \copy2.a_reg_next ;
  assign \copy2.a_reg_next_same  = 1'h0;
  assign \copy2.a_reg_other  = a_reg1;
  assign \copy2.a_reg_other_next  = a_reg1_next;
  assign \copy2.a_reg_same  = _006_[0];
  assign \copy2.b  = b;
  assign b_reg2 = \copy2.b_reg ;
  assign b_reg2_next = \copy2.b_reg_next ;
  assign \copy2.b_reg_next_same  = 1'h0;
  assign \copy2.b_reg_other  = b_reg1;
  assign \copy2.b_reg_other_next  = b_reg1_next;
  assign \copy2.b_reg_same  = _056_[0];
  assign busy2 = \copy2.busy ;
  assign busy2_next = \copy2.busy_next ;
  assign \copy2.busy_next_same  = 1'h0;
  assign \copy2.busy_other  = busy1;
  assign \copy2.busy_other_next  = busy1_next;
  assign \copy2.busy_same  = _008_[0];
  assign \copy2.clk  = clk;
  assign counter2 = \copy2.counter ;
  assign counter2_next = \copy2.counter_next ;
  assign \copy2.counter_next_same  = 1'h0;
  assign \copy2.counter_other  = counter1;
  assign \copy2.counter_other_next  = counter1_next;
  assign \copy2.counter_same  = _057_[0];
  assign finish2 = \copy2.finish ;
  assign finish2_next = \copy2.finish_next ;
  assign \copy2.finish_next_same  = 1'h0;
  assign \copy2.finish_other  = finish1;
  assign \copy2.finish_other_next  = finish1_next;
  assign \copy2.finish_same  = _058_[0];
  assign \copy2.in_valid  = in_valid;
  assign o2 = \copy2.o ;
  assign o2_next = \copy2.o_reg_next ;
  assign \copy2.o_reg_next_same  = 1'h0;
  assign \copy2.o_reg_other  = o1;
  assign \copy2.o_reg_other_next  = o1_next;
  assign \copy2.o_reg_same  = _007_[0];
  assign out_valid2 = \copy2.out_valid ;
  assign \copy2.pause  = pause_2;
  assign _019_[31:4] = 28'b000000000000000000000000000x;
  assign _020_[31:16] = 16'hxxxx;
  assign _021_[31:16] = 16'hxxxx;
  assign \copy1.o  = \copy1.o_reg_this ;
  assign \copy1.out_valid  = \copy1.finish_this ;
  assign \copy1.a  = a1;
  assign a_reg1 = \copy1.a_reg ;
  assign a_reg1_next = \copy1.a_reg_next ;
  assign \copy1.a_reg_next_same  = 1'h0;
  assign \copy1.a_reg_same  = 1'h0;
  assign \copy1.b  = b;
  assign b_reg1 = \copy1.b_reg ;
  assign b_reg1_next = \copy1.b_reg_next ;
  assign \copy1.b_reg_next_same  = 1'h0;
  assign \copy1.b_reg_same  = 1'h0;
  assign busy1 = \copy1.busy ;
  assign busy1_next = \copy1.busy_next ;
  assign \copy1.busy_next_same  = 1'h0;
  assign \copy1.busy_same  = 1'h0;
  assign \copy1.clk  = clk;
  assign counter1 = \copy1.counter ;
  assign counter1_next = \copy1.counter_next ;
  assign \copy1.counter_next_same  = 1'h0;
  assign \copy1.counter_same  = 1'h0;
  assign finish1 = \copy1.finish ;
  assign finish1_next = \copy1.finish_next ;
  assign \copy1.finish_next_same  = 1'h0;
  assign \copy1.finish_same  = 1'h0;
  assign \copy1.in_valid  = in_valid;
  assign o1 = \copy1.o ;
  assign o1_next = \copy1.o_reg_next ;
  assign \copy1.o_reg_next_same  = 1'h0;
  assign \copy1.o_reg_same  = 1'h0;
  assign out_valid1 = \copy1.out_valid ;
  assign \copy1.pause  = pause_1;
endmodule
