/* Generated by Yosys 0.9+3833 (git sha1 b0004911c, gcc 15.0.0 -fPIC -Os) */

module alu(clk, _12_, _13_, _14_, _15_, _16_, _05_);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  output _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  input _12_;
  input _13_;
  input _14_;
  input _15_;
  input _16_;
  reg _17_ = 1'h0;
  reg _18_ = 1'h0;
  input clk;
  assign _01_ = _11_ & _09_;
  assign _03_ = _15_ & _14_;
  assign _04_ = _03_ & _06_;
  assign _05_ = _02_ & _00_;
  assign _08_ = _18_ & _17_;
  assign _10_ = _07_ & _16_;
  always @(posedge clk)
    _17_ <= _04_;
  always @(posedge clk)
    _18_ <= _00_;
  assign _00_ = ~1'h0;
  assign _02_ = ~_01_;
  assign _06_ = ~_13_;
  assign _07_ = ~_18_;
  assign _09_ = ~_08_;
  assign _11_ = ~_10_;
endmodule
