/* Generated by Yosys 0.42+36 (git sha1 07daf61ae, clang++ 15.0.0 -fPIC -Os) */

(* keep =  1  *)
(* top =  1  *)
(* src = "multiplier_sc.sv:20.1-262.10" *)
module multiplier_sc(clk, a1, a2, b, in_valid);
  (* src = "multiplier_sc.sv:171.1-175.4" *)
  wire _000_;
  (* src = "multiplier_sc.sv:207.25-207.31" *)
  wire _001_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  wire _002_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  wire _003_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  wire _004_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  wire _005_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  wire _006_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  wire [1:0] _007_;
  wire _008_;
  wire [1:0] _009_;
  (* src = "multiplier_sc.sv:366.113-366.139" *)
  (* unused_bits = "2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _010_;
  (* src = "multiplier_sc.sv:366.66-366.144" *)
  wire [31:0] _011_;
  (* src = "multiplier_sc.sv:362.48-362.63" *)
  wire _012_;
  (* src = "multiplier_sc.sv:362.73-362.88" *)
  wire _013_;
  (* src = "multiplier_sc.sv:361.42-361.64" *)
  wire _014_;
  (* src = "multiplier_sc.sv:361.68-361.93" *)
  wire _015_;
  (* src = "multiplier_sc.sv:362.46-362.103" *)
  wire _016_;
  (* src = "multiplier_sc.sv:361.68-361.80" *)
  wire _017_;
  (* src = "multiplier_sc.sv:361.42-361.93" *)
  wire _018_;
  (* src = "multiplier_sc.sv:362.47-362.89" *)
  wire _019_;
  (* src = "multiplier_sc.sv:363.59-363.98" *)
  wire _020_;
  (* src = "multiplier_sc.sv:364.59-364.103" *)
  wire _021_;
  (* src = "multiplier_sc.sv:365.54-365.87" *)
  wire [31:0] _022_;
  (* src = "multiplier_sc.sv:366.97-366.143" *)
  wire [31:0] _023_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  wire _024_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  wire _025_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  wire _026_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  wire _027_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  wire _028_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  wire [1:0] _029_;
  wire _030_;
  wire [1:0] _031_;
  (* src = "multiplier_sc.sv:366.113-366.139" *)
  (* unused_bits = "2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _032_;
  (* src = "multiplier_sc.sv:366.66-366.144" *)
  wire [31:0] _033_;
  (* src = "multiplier_sc.sv:362.48-362.63" *)
  wire _034_;
  (* src = "multiplier_sc.sv:362.73-362.88" *)
  wire _035_;
  (* src = "multiplier_sc.sv:361.42-361.64" *)
  wire _036_;
  (* src = "multiplier_sc.sv:361.68-361.93" *)
  wire _037_;
  (* src = "multiplier_sc.sv:362.46-362.103" *)
  wire _038_;
  (* src = "multiplier_sc.sv:361.68-361.80" *)
  wire _039_;
  (* src = "multiplier_sc.sv:361.42-361.93" *)
  wire _040_;
  (* src = "multiplier_sc.sv:362.47-362.89" *)
  wire _041_;
  (* src = "multiplier_sc.sv:363.59-363.98" *)
  wire _042_;
  (* src = "multiplier_sc.sv:364.59-364.103" *)
  wire _043_;
  (* src = "multiplier_sc.sv:365.54-365.87" *)
  wire [31:0] _044_;
  (* src = "multiplier_sc.sv:366.97-366.143" *)
  wire [31:0] _045_;
  (* src = "multiplier_sc.sv:174.17-174.42" *)
  wire _046_;
  (* src = "multiplier_sc.sv:174.46-174.71" *)
  wire _047_;
  (* src = "multiplier_sc.sv:176.18-176.33" *)
  wire _048_;
  (* src = "multiplier_sc.sv:177.18-177.33" *)
  wire _049_;
  (* src = "multiplier_sc.sv:207.23-207.46" *)
  wire _050_;
  (* src = "multiplier_sc.sv:207.23-207.60" *)
  wire _051_;
  (* src = "multiplier_sc.sv:176.37-176.48" *)
  wire _052_;
  (* src = "multiplier_sc.sv:177.37-177.48" *)
  wire _053_;
  (* src = "multiplier_sc.sv:207.23-207.32" *)
  wire _054_;
  (* src = "multiplier_sc.sv:244.36-244.44" *)
  wire _055_;
  (* src = "multiplier_sc.sv:119.12-119.32" *)
  wire _056_;
  (* src = "multiplier_sc.sv:164.12-164.32" *)
  wire _057_;
  (* src = "multiplier_sc.sv:244.18-244.44" *)
  wire _058_;
  (* src = "multiplier_sc.sv:22.26-22.28" *)
  input a1;
  wire a1;
  (* src = "multiplier_sc.sv:23.26-23.28" *)
  input a2;
  wire a2;
  (* src = "multiplier_sc.sv:31.21-31.27" *)
  wire a_reg1;
  (* src = "multiplier_sc.sv:31.29-31.40" *)
  wire a_reg1_next;
  (* src = "multiplier_sc.sv:31.42-31.48" *)
  (* unused_bits = "0" *)
  wire a_reg2;
  (* src = "multiplier_sc.sv:31.50-31.61" *)
  (* unused_bits = "0" *)
  wire a_reg2_next;
  (* src = "multiplier_sc.sv:66.6-66.19" *)
  wire a_reg_diff_in;
  (* src = "multiplier_sc.sv:49.6-49.21" *)
  wire a_reg_next_same;
  (* src = "multiplier_sc.sv:181.6-181.15" *)
  wire all_pause;
  (* src = "multiplier_sc.sv:189.6-189.25" *)
  wire assume_1_violate_in;
  (* src = "multiplier_sc.sv:199.6-199.25" *)
  wire assume_2_violate_in;
  (* src = "multiplier_sc.sv:212.6-212.25" *)
  wire assume_3_violate_in;
  (* src = "multiplier_sc.sv:225.6-225.33" *)
  wire assume_predicate_violate_in;
  (* src = "multiplier_sc.sv:39.6-39.20" *)
  wire assume_violate;
  (* src = "multiplier_sc.sv:24.26-24.27" *)
  input b;
  wire b;
  (* src = "multiplier_sc.sv:31.63-31.69" *)
  wire b_reg1;
  (* src = "multiplier_sc.sv:31.71-31.82" *)
  wire b_reg1_next;
  (* src = "multiplier_sc.sv:31.84-31.90" *)
  (* unused_bits = "0" *)
  wire b_reg2;
  (* src = "multiplier_sc.sv:31.92-31.103" *)
  (* unused_bits = "0" *)
  wire b_reg2_next;
  (* src = "multiplier_sc.sv:67.6-67.19" *)
  wire b_reg_diff_in;
  (* src = "multiplier_sc.sv:50.6-50.21" *)
  wire b_reg_next_same;
  (* src = "multiplier_sc.sv:30.6-30.11" *)
  wire busy1;
  (* src = "multiplier_sc.sv:30.13-30.23" *)
  wire busy1_next;
  (* src = "multiplier_sc.sv:30.25-30.30" *)
  (* unused_bits = "0" *)
  wire busy2;
  (* src = "multiplier_sc.sv:30.32-30.42" *)
  (* unused_bits = "0" *)
  wire busy2_next;
  (* src = "multiplier_sc.sv:71.6-71.18" *)
  wire busy_diff_in;
  (* src = "multiplier_sc.sv:53.6-53.20" *)
  wire busy_next_same;
  (* src = "multiplier_sc.sv:21.11-21.14" *)
  input clk;
  wire clk;
  (* hdlname = "copy1 a" *)
  (* src = "multiplier_sc.sv:269.26-269.27" *)
  wire \copy1.a ;
  (* hdlname = "copy1 a_reg" *)
  (* src = "multiplier_sc.sv:276.27-276.32" *)
  reg \copy1.a_reg  = 1'h0;
  (* hdlname = "copy1 a_reg_next" *)
  (* src = "multiplier_sc.sv:281.27-281.37" *)
  wire \copy1.a_reg_next ;
  (* hdlname = "copy1 a_reg_next_same" *)
  (* src = "multiplier_sc.sv:292.11-292.26" *)
  wire \copy1.a_reg_next_same ;
  (* hdlname = "copy1 a_reg_other" *)
  (* src = "multiplier_sc.sv:298.26-298.37" *)
  wire \copy1.a_reg_other ;
  (* hdlname = "copy1 a_reg_other_next" *)
  (* src = "multiplier_sc.sv:304.26-304.42" *)
  wire \copy1.a_reg_other_next ;
  (* hdlname = "copy1 a_reg_same" *)
  (* src = "multiplier_sc.sv:286.11-286.21" *)
  wire \copy1.a_reg_same ;
  (* hdlname = "copy1 a_reg_this" *)
  (* src = "multiplier_sc.sv:328.25-328.35" *)
  wire \copy1.a_reg_this ;
  (* hdlname = "copy1 b" *)
  (* src = "multiplier_sc.sv:270.26-270.27" *)
  wire \copy1.b ;
  (* hdlname = "copy1 b_reg" *)
  (* src = "multiplier_sc.sv:277.27-277.32" *)
  reg \copy1.b_reg  = 1'h0;
  (* hdlname = "copy1 b_reg_next" *)
  (* src = "multiplier_sc.sv:282.27-282.37" *)
  wire \copy1.b_reg_next ;
  (* hdlname = "copy1 b_reg_next_same" *)
  (* src = "multiplier_sc.sv:293.11-293.26" *)
  wire \copy1.b_reg_next_same ;
  (* hdlname = "copy1 b_reg_other" *)
  (* src = "multiplier_sc.sv:299.26-299.37" *)
  wire \copy1.b_reg_other ;
  (* hdlname = "copy1 b_reg_other_next" *)
  (* src = "multiplier_sc.sv:305.26-305.42" *)
  wire \copy1.b_reg_other_next ;
  (* hdlname = "copy1 b_reg_same" *)
  (* src = "multiplier_sc.sv:287.11-287.21" *)
  wire \copy1.b_reg_same ;
  (* hdlname = "copy1 b_reg_this" *)
  (* src = "multiplier_sc.sv:329.25-329.35" *)
  wire \copy1.b_reg_this ;
  (* hdlname = "copy1 busy" *)
  (* src = "multiplier_sc.sv:274.12-274.16" *)
  reg \copy1.busy  = 1'h0;
  (* hdlname = "copy1 busy_next" *)
  (* src = "multiplier_sc.sv:279.12-279.21" *)
  wire \copy1.busy_next ;
  (* hdlname = "copy1 busy_next_same" *)
  (* src = "multiplier_sc.sv:296.11-296.25" *)
  wire \copy1.busy_next_same ;
  (* hdlname = "copy1 busy_other" *)
  (* src = "multiplier_sc.sv:302.11-302.21" *)
  wire \copy1.busy_other ;
  (* hdlname = "copy1 busy_other_next" *)
  (* src = "multiplier_sc.sv:308.11-308.26" *)
  wire \copy1.busy_other_next ;
  (* hdlname = "copy1 busy_same" *)
  (* src = "multiplier_sc.sv:290.11-290.20" *)
  wire \copy1.busy_same ;
  (* hdlname = "copy1 busy_this" *)
  (* src = "multiplier_sc.sv:326.10-326.19" *)
  wire \copy1.busy_this ;
  (* hdlname = "copy1 clk" *)
  (* src = "multiplier_sc.sv:267.11-267.14" *)
  wire \copy1.clk ;
  (* hdlname = "copy1 counter" *)
  (* src = "multiplier_sc.sv:278.18-278.25" *)
  reg \copy1.counter ;
  (* hdlname = "copy1 counter_next" *)
  (* src = "multiplier_sc.sv:284.18-284.30" *)
  wire \copy1.counter_next ;
  (* hdlname = "copy1 counter_next_same" *)
  (* src = "multiplier_sc.sv:295.11-295.28" *)
  wire \copy1.counter_next_same ;
  (* hdlname = "copy1 counter_other" *)
  (* src = "multiplier_sc.sv:301.17-301.30" *)
  wire \copy1.counter_other ;
  (* hdlname = "copy1 counter_other_next" *)
  (* src = "multiplier_sc.sv:307.17-307.35" *)
  wire \copy1.counter_other_next ;
  (* hdlname = "copy1 counter_same" *)
  (* src = "multiplier_sc.sv:289.11-289.23" *)
  wire \copy1.counter_same ;
  (* hdlname = "copy1 counter_this" *)
  (* src = "multiplier_sc.sv:330.16-330.28" *)
  wire \copy1.counter_this ;
  (* hdlname = "copy1 finish" *)
  (* src = "multiplier_sc.sv:275.12-275.18" *)
  reg \copy1.finish  = 1'h0;
  (* hdlname = "copy1 finish_next" *)
  (* src = "multiplier_sc.sv:280.12-280.23" *)
  wire \copy1.finish_next ;
  (* hdlname = "copy1 finish_next_same" *)
  (* src = "multiplier_sc.sv:297.11-297.27" *)
  wire \copy1.finish_next_same ;
  (* hdlname = "copy1 finish_other" *)
  (* src = "multiplier_sc.sv:303.11-303.23" *)
  wire \copy1.finish_other ;
  (* hdlname = "copy1 finish_other_next" *)
  (* src = "multiplier_sc.sv:309.11-309.28" *)
  wire \copy1.finish_other_next ;
  (* hdlname = "copy1 finish_same" *)
  (* src = "multiplier_sc.sv:291.11-291.22" *)
  wire \copy1.finish_same ;
  (* hdlname = "copy1 finish_this" *)
  (* src = "multiplier_sc.sv:327.10-327.21" *)
  wire \copy1.finish_this ;
  (* hdlname = "copy1 in_ready" *)
  (* src = "multiplier_sc.sv:273.12-273.20" *)
  wire \copy1.in_ready ;
  (* hdlname = "copy1 in_valid" *)
  (* src = "multiplier_sc.sv:268.11-268.19" *)
  wire \copy1.in_valid ;
  (* hdlname = "copy1 o" *)
  (* src = "multiplier_sc.sv:271.34-271.35" *)
  wire [1:0] \copy1.o ;
  (* hdlname = "copy1 o_reg" *)
  (* src = "multiplier_sc.sv:313.31-313.36" *)
  reg [1:0] \copy1.o_reg  = 2'h0;
  (* hdlname = "copy1 o_reg_next" *)
  (* src = "multiplier_sc.sv:283.34-283.44" *)
  wire [1:0] \copy1.o_reg_next ;
  (* hdlname = "copy1 o_reg_next_same" *)
  (* src = "multiplier_sc.sv:294.11-294.26" *)
  wire \copy1.o_reg_next_same ;
  (* hdlname = "copy1 o_reg_other" *)
  (* src = "multiplier_sc.sv:300.33-300.44" *)
  wire [1:0] \copy1.o_reg_other ;
  (* hdlname = "copy1 o_reg_other_next" *)
  (* src = "multiplier_sc.sv:306.33-306.49" *)
  wire [1:0] \copy1.o_reg_other_next ;
  (* hdlname = "copy1 o_reg_same" *)
  (* src = "multiplier_sc.sv:288.11-288.21" *)
  wire \copy1.o_reg_same ;
  (* hdlname = "copy1 o_reg_this" *)
  (* src = "multiplier_sc.sv:331.32-331.42" *)
  wire [1:0] \copy1.o_reg_this ;
  (* hdlname = "copy1 out_valid" *)
  (* src = "multiplier_sc.sv:272.12-272.21" *)
  wire \copy1.out_valid ;
  (* hdlname = "copy1 pause" *)
  (* src = "multiplier_sc.sv:310.11-310.16" *)
  wire \copy1.pause ;
  (* hdlname = "copy2 a" *)
  (* src = "multiplier_sc.sv:269.26-269.27" *)
  wire \copy2.a ;
  (* hdlname = "copy2 a_reg" *)
  (* src = "multiplier_sc.sv:276.27-276.32" *)
  reg \copy2.a_reg  = 1'h0;
  (* hdlname = "copy2 a_reg_next" *)
  (* src = "multiplier_sc.sv:281.27-281.37" *)
  wire \copy2.a_reg_next ;
  (* hdlname = "copy2 a_reg_next_same" *)
  (* src = "multiplier_sc.sv:292.11-292.26" *)
  wire \copy2.a_reg_next_same ;
  (* hdlname = "copy2 a_reg_other" *)
  (* src = "multiplier_sc.sv:298.26-298.37" *)
  wire \copy2.a_reg_other ;
  (* hdlname = "copy2 a_reg_other_next" *)
  (* src = "multiplier_sc.sv:304.26-304.42" *)
  wire \copy2.a_reg_other_next ;
  (* hdlname = "copy2 a_reg_same" *)
  (* src = "multiplier_sc.sv:286.11-286.21" *)
  wire \copy2.a_reg_same ;
  (* hdlname = "copy2 a_reg_this" *)
  (* src = "multiplier_sc.sv:328.25-328.35" *)
  wire \copy2.a_reg_this ;
  (* hdlname = "copy2 b" *)
  (* src = "multiplier_sc.sv:270.26-270.27" *)
  wire \copy2.b ;
  (* hdlname = "copy2 b_reg" *)
  (* src = "multiplier_sc.sv:277.27-277.32" *)
  reg \copy2.b_reg  = 1'h0;
  (* hdlname = "copy2 b_reg_next" *)
  (* src = "multiplier_sc.sv:282.27-282.37" *)
  wire \copy2.b_reg_next ;
  (* hdlname = "copy2 b_reg_next_same" *)
  (* src = "multiplier_sc.sv:293.11-293.26" *)
  wire \copy2.b_reg_next_same ;
  (* hdlname = "copy2 b_reg_other" *)
  (* src = "multiplier_sc.sv:299.26-299.37" *)
  wire \copy2.b_reg_other ;
  (* hdlname = "copy2 b_reg_other_next" *)
  (* src = "multiplier_sc.sv:305.26-305.42" *)
  wire \copy2.b_reg_other_next ;
  (* hdlname = "copy2 b_reg_same" *)
  (* src = "multiplier_sc.sv:287.11-287.21" *)
  wire \copy2.b_reg_same ;
  (* hdlname = "copy2 b_reg_this" *)
  (* src = "multiplier_sc.sv:329.25-329.35" *)
  wire \copy2.b_reg_this ;
  (* hdlname = "copy2 busy" *)
  (* src = "multiplier_sc.sv:274.12-274.16" *)
  reg \copy2.busy  = 1'h0;
  (* hdlname = "copy2 busy_next" *)
  (* src = "multiplier_sc.sv:279.12-279.21" *)
  wire \copy2.busy_next ;
  (* hdlname = "copy2 busy_next_same" *)
  (* src = "multiplier_sc.sv:296.11-296.25" *)
  wire \copy2.busy_next_same ;
  (* hdlname = "copy2 busy_other" *)
  (* src = "multiplier_sc.sv:302.11-302.21" *)
  wire \copy2.busy_other ;
  (* hdlname = "copy2 busy_other_next" *)
  (* src = "multiplier_sc.sv:308.11-308.26" *)
  wire \copy2.busy_other_next ;
  (* hdlname = "copy2 busy_same" *)
  (* src = "multiplier_sc.sv:290.11-290.20" *)
  wire \copy2.busy_same ;
  (* hdlname = "copy2 busy_this" *)
  (* src = "multiplier_sc.sv:326.10-326.19" *)
  wire \copy2.busy_this ;
  (* hdlname = "copy2 clk" *)
  (* src = "multiplier_sc.sv:267.11-267.14" *)
  wire \copy2.clk ;
  (* hdlname = "copy2 counter" *)
  (* src = "multiplier_sc.sv:278.18-278.25" *)
  reg \copy2.counter ;
  (* hdlname = "copy2 counter_next" *)
  (* src = "multiplier_sc.sv:284.18-284.30" *)
  wire \copy2.counter_next ;
  (* hdlname = "copy2 counter_next_same" *)
  (* src = "multiplier_sc.sv:295.11-295.28" *)
  wire \copy2.counter_next_same ;
  (* hdlname = "copy2 counter_other" *)
  (* src = "multiplier_sc.sv:301.17-301.30" *)
  wire \copy2.counter_other ;
  (* hdlname = "copy2 counter_other_next" *)
  (* src = "multiplier_sc.sv:307.17-307.35" *)
  wire \copy2.counter_other_next ;
  (* hdlname = "copy2 counter_same" *)
  (* src = "multiplier_sc.sv:289.11-289.23" *)
  wire \copy2.counter_same ;
  (* hdlname = "copy2 counter_this" *)
  (* src = "multiplier_sc.sv:330.16-330.28" *)
  wire \copy2.counter_this ;
  (* hdlname = "copy2 finish" *)
  (* src = "multiplier_sc.sv:275.12-275.18" *)
  reg \copy2.finish  = 1'h0;
  (* hdlname = "copy2 finish_next" *)
  (* src = "multiplier_sc.sv:280.12-280.23" *)
  wire \copy2.finish_next ;
  (* hdlname = "copy2 finish_next_same" *)
  (* src = "multiplier_sc.sv:297.11-297.27" *)
  wire \copy2.finish_next_same ;
  (* hdlname = "copy2 finish_other" *)
  (* src = "multiplier_sc.sv:303.11-303.23" *)
  wire \copy2.finish_other ;
  (* hdlname = "copy2 finish_other_next" *)
  (* src = "multiplier_sc.sv:309.11-309.28" *)
  wire \copy2.finish_other_next ;
  (* hdlname = "copy2 finish_same" *)
  (* src = "multiplier_sc.sv:291.11-291.22" *)
  wire \copy2.finish_same ;
  (* hdlname = "copy2 finish_this" *)
  (* src = "multiplier_sc.sv:327.10-327.21" *)
  wire \copy2.finish_this ;
  (* hdlname = "copy2 in_ready" *)
  (* src = "multiplier_sc.sv:273.12-273.20" *)
  wire \copy2.in_ready ;
  (* hdlname = "copy2 in_valid" *)
  (* src = "multiplier_sc.sv:268.11-268.19" *)
  wire \copy2.in_valid ;
  (* hdlname = "copy2 o" *)
  (* src = "multiplier_sc.sv:271.34-271.35" *)
  wire [1:0] \copy2.o ;
  (* hdlname = "copy2 o_reg" *)
  (* src = "multiplier_sc.sv:313.31-313.36" *)
  reg [1:0] \copy2.o_reg  = 2'h0;
  (* hdlname = "copy2 o_reg_next" *)
  (* src = "multiplier_sc.sv:283.34-283.44" *)
  wire [1:0] \copy2.o_reg_next ;
  (* hdlname = "copy2 o_reg_next_same" *)
  (* src = "multiplier_sc.sv:294.11-294.26" *)
  wire \copy2.o_reg_next_same ;
  (* hdlname = "copy2 o_reg_other" *)
  (* src = "multiplier_sc.sv:300.33-300.44" *)
  wire [1:0] \copy2.o_reg_other ;
  (* hdlname = "copy2 o_reg_other_next" *)
  (* src = "multiplier_sc.sv:306.33-306.49" *)
  wire [1:0] \copy2.o_reg_other_next ;
  (* hdlname = "copy2 o_reg_same" *)
  (* src = "multiplier_sc.sv:288.11-288.21" *)
  wire \copy2.o_reg_same ;
  (* hdlname = "copy2 o_reg_this" *)
  (* src = "multiplier_sc.sv:331.32-331.42" *)
  wire [1:0] \copy2.o_reg_this ;
  (* hdlname = "copy2 out_valid" *)
  (* src = "multiplier_sc.sv:272.12-272.21" *)
  wire \copy2.out_valid ;
  (* hdlname = "copy2 pause" *)
  (* src = "multiplier_sc.sv:310.11-310.16" *)
  wire \copy2.pause ;
  (* src = "multiplier_sc.sv:32.12-32.20" *)
  wire counter1;
  (* src = "multiplier_sc.sv:32.22-32.35" *)
  wire counter1_next;
  (* src = "multiplier_sc.sv:32.37-32.45" *)
  (* unused_bits = "0" *)
  wire counter2;
  (* src = "multiplier_sc.sv:32.47-32.60" *)
  (* unused_bits = "0" *)
  wire counter2_next;
  (* src = "multiplier_sc.sv:69.6-69.21" *)
  wire counter_diff_in;
  (* src = "multiplier_sc.sv:52.6-52.23" *)
  wire counter_next_same;
  (* src = "multiplier_sc.sv:170.5-170.12" *)
  reg drained;
  (* src = "multiplier_sc.sv:30.44-30.51" *)
  wire finish1;
  (* src = "multiplier_sc.sv:30.53-30.65" *)
  wire finish1_next;
  (* src = "multiplier_sc.sv:30.67-30.74" *)
  (* unused_bits = "0" *)
  wire finish2;
  (* src = "multiplier_sc.sv:30.76-30.88" *)
  (* unused_bits = "0" *)
  wire finish2_next;
  (* src = "multiplier_sc.sv:70.6-70.20" *)
  wire finish_diff_in;
  (* src = "multiplier_sc.sv:54.6-54.22" *)
  wire finish_next_same;
  (* src = "multiplier_sc.sv:25.11-25.19" *)
  input in_valid;
  wire in_valid;
  (* src = "multiplier_sc.sv:28.28-28.30" *)
  wire [1:0] o1;
  (* src = "multiplier_sc.sv:28.32-28.39" *)
  wire [1:0] o1_next;
  (* src = "multiplier_sc.sv:28.41-28.43" *)
  wire [1:0] o2;
  (* src = "multiplier_sc.sv:28.45-28.52" *)
  (* unused_bits = "0 1" *)
  wire [1:0] o2_next;
  (* src = "multiplier_sc.sv:206.5-206.16" *)
  reg o_ever_diff = 1'h0;
  (* src = "multiplier_sc.sv:207.6-207.20" *)
  wire o_ever_diff_in;
  (* src = "multiplier_sc.sv:68.6-68.19" *)
  wire o_reg_diff_in;
  (* src = "multiplier_sc.sv:51.6-51.21" *)
  wire o_reg_next_same;
  (* src = "multiplier_sc.sv:29.6-29.16" *)
  wire out_valid1;
  (* src = "multiplier_sc.sv:29.18-29.28" *)
  wire out_valid2;
  (* src = "multiplier_sc.sv:168.6-168.13" *)
  wire pause_1;
  (* src = "multiplier_sc.sv:169.5-169.16" *)
  reg pause_1_reg;
  (* src = "multiplier_sc.sv:168.15-168.22" *)
  wire pause_2;
  (* src = "multiplier_sc.sv:169.18-169.29" *)
  reg pause_2_reg;
  always @* if (1'h1) assert(_058_);
  assign _001_ = o1 == (* src = "multiplier_sc.sv:207.25-207.31" *) o2;
  assign _008_ = \copy1.counter_this  + (* src = "multiplier_sc.sv:365.71-365.87" *) 1'h1;
  assign _009_ = \copy1.o_reg_this  + (* src = "multiplier_sc.sv:366.83-366.144" *) _023_[1:0];
  assign _012_ = ~ (* src = "multiplier_sc.sv:362.48-362.63" *) \copy1.a_reg_this ;
  assign _013_ = ~ (* src = "multiplier_sc.sv:362.73-362.88" *) \copy1.b_reg_this ;
  assign _014_ = \copy1.in_valid  && (* src = "multiplier_sc.sv:361.42-361.64" *) \copy1.in_ready ;
  assign _015_ = _017_ && (* src = "multiplier_sc.sv:361.68-361.93" *) \copy1.busy_this ;
  assign _016_ = _019_ && (* src = "multiplier_sc.sv:362.46-362.103" *) \copy1.busy_this ;
  assign \copy1.in_ready  = ! (* src = "multiplier_sc.sv:361.54-361.64" *) \copy1.busy_this ;
  assign _017_ = ! (* src = "multiplier_sc.sv:361.68-361.80" *) \copy1.finish_next ;
  assign _018_ = _014_ || (* src = "multiplier_sc.sv:361.42-361.93" *) _015_;
  assign _019_ = _012_ || (* src = "multiplier_sc.sv:362.47-362.89" *) _013_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  always @(posedge \copy1.clk )
    \copy1.a_reg  <= _002_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  always @(posedge \copy1.clk )
    \copy1.b_reg  <= _003_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  always @(posedge \copy1.clk )
    \copy1.counter  <= _005_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  always @(posedge \copy1.clk )
    \copy1.busy  <= _004_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  always @(posedge \copy1.clk )
    \copy1.finish  <= _006_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  always @(posedge \copy1.clk )
    \copy1.o_reg  <= _007_;
  assign _010_[1:0] = \copy1.a_reg_this  << (* src = "multiplier_sc.sv:366.113-366.139" *) \copy1.counter_this ;
  assign \copy1.busy_this  = \copy1.busy_same  ? (* src = "multiplier_sc.sv:326.22-326.51" *) \copy1.busy_other  : \copy1.busy ;
  assign \copy1.finish_this  = \copy1.finish_same  ? (* src = "multiplier_sc.sv:327.24-327.59" *) \copy1.finish_other  : \copy1.finish ;
  assign \copy1.a_reg_this  = \copy1.a_reg_same  ? (* src = "multiplier_sc.sv:328.38-328.70" *) \copy1.a_reg_other  : \copy1.a_reg ;
  assign \copy1.b_reg_this  = \copy1.b_reg_same  ? (* src = "multiplier_sc.sv:329.38-329.70" *) \copy1.b_reg_other  : \copy1.b_reg ;
  assign \copy1.counter_this  = \copy1.counter_same  ? (* src = "multiplier_sc.sv:330.31-330.69" *) \copy1.counter_other  : \copy1.counter ;
  assign \copy1.o_reg_this  = \copy1.o_reg_same  ? (* src = "multiplier_sc.sv:331.45-331.77" *) \copy1.o_reg_other  : \copy1.o_reg ;
  assign \copy1.busy_next  = \copy1.pause  ? (* src = "multiplier_sc.sv:361.22-361.93" *) \copy1.busy_this  : _018_;
  assign \copy1.finish_next  = \copy1.pause  ? (* src = "multiplier_sc.sv:362.24-362.103" *) \copy1.finish_this  : _016_;
  assign _020_ = _014_ ? (* src = "multiplier_sc.sv:363.59-363.98" *) \copy1.a  : \copy1.a_reg_this ;
  assign \copy1.a_reg_next  = \copy1.pause  ? (* src = "multiplier_sc.sv:363.38-363.98" *) \copy1.a_reg_this  : _020_;
  assign _021_ = _014_ ? (* src = "multiplier_sc.sv:364.59-364.103" *) \copy1.b  : 1'h0;
  assign \copy1.b_reg_next  = \copy1.pause  ? (* src = "multiplier_sc.sv:364.38-364.103" *) \copy1.b_reg_this  : _021_;
  assign _022_[0] = \copy1.busy_this  ? (* src = "multiplier_sc.sv:365.54-365.87" *) _008_ : 1'h0;
  assign \copy1.counter_next  = \copy1.pause  ? (* src = "multiplier_sc.sv:365.31-365.87" *) \copy1.counter_this  : _022_[0];
  assign _023_[1:0] = \copy1.b_reg_this  ? (* src = "multiplier_sc.sv:366.97-366.143" *) _010_[1:0] : 2'h0;
  assign _011_[1:0] = \copy1.busy_this  ? (* src = "multiplier_sc.sv:366.66-366.144" *) _009_ : 2'h0;
  assign \copy1.o_reg_next  = \copy1.pause  ? (* src = "multiplier_sc.sv:366.45-366.144" *) \copy1.o_reg_this  : _011_[1:0];
  assign _006_ = \copy1.finish_next_same  ? (* src = "multiplier_sc.sv:370.19-370.69" *) \copy1.finish_other_next  : \copy1.finish_next ;
  assign _004_ = \copy1.busy_next_same  ? (* src = "multiplier_sc.sv:371.17-371.61" *) \copy1.busy_other_next  : \copy1.busy_next ;
  assign _002_ = \copy1.a_reg_next_same  ? (* src = "multiplier_sc.sv:372.18-372.65" *) \copy1.a_reg_other_next  : \copy1.a_reg_next ;
  assign _003_ = \copy1.b_reg_next_same  ? (* src = "multiplier_sc.sv:373.18-373.65" *) \copy1.b_reg_other_next  : \copy1.b_reg_next ;
  assign _005_ = \copy1.counter_next_same  ? (* src = "multiplier_sc.sv:374.20-374.73" *) \copy1.counter_other_next  : \copy1.counter_next ;
  assign _007_ = \copy1.o_reg_next_same  ? (* src = "multiplier_sc.sv:375.18-375.65" *) \copy1.o_reg_other_next  : \copy1.o_reg_next ;
  assign _030_ = \copy2.counter_this  + (* src = "multiplier_sc.sv:365.71-365.87" *) 1'h1;
  assign _031_ = \copy2.o_reg_this  + (* src = "multiplier_sc.sv:366.83-366.144" *) _045_[1:0];
  assign _034_ = ~ (* src = "multiplier_sc.sv:362.48-362.63" *) \copy2.a_reg_this ;
  assign _035_ = ~ (* src = "multiplier_sc.sv:362.73-362.88" *) \copy2.b_reg_this ;
  assign _036_ = \copy2.in_valid  && (* src = "multiplier_sc.sv:361.42-361.64" *) \copy2.in_ready ;
  assign _037_ = _039_ && (* src = "multiplier_sc.sv:361.68-361.93" *) \copy2.busy_this ;
  assign _038_ = _041_ && (* src = "multiplier_sc.sv:362.46-362.103" *) \copy2.busy_this ;
  assign \copy2.in_ready  = ! (* src = "multiplier_sc.sv:361.54-361.64" *) \copy2.busy_this ;
  assign _039_ = ! (* src = "multiplier_sc.sv:361.68-361.80" *) \copy2.finish_next ;
  assign _040_ = _036_ || (* src = "multiplier_sc.sv:361.42-361.93" *) _037_;
  assign _041_ = _034_ || (* src = "multiplier_sc.sv:362.47-362.89" *) _035_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  always @(posedge \copy2.clk )
    \copy2.a_reg  <= _024_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  always @(posedge \copy2.clk )
    \copy2.b_reg  <= _025_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  always @(posedge \copy2.clk )
    \copy2.counter  <= _027_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  always @(posedge \copy2.clk )
    \copy2.busy  <= _026_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  always @(posedge \copy2.clk )
    \copy2.finish  <= _028_;
  (* src = "multiplier_sc.sv:369.5-376.8" *)
  always @(posedge \copy2.clk )
    \copy2.o_reg  <= _029_;
  assign _032_[1:0] = \copy2.a_reg_this  << (* src = "multiplier_sc.sv:366.113-366.139" *) \copy2.counter_this ;
  assign \copy2.busy_this  = \copy2.busy_same  ? (* src = "multiplier_sc.sv:326.22-326.51" *) \copy2.busy_other  : \copy2.busy ;
  assign \copy2.finish_this  = \copy2.finish_same  ? (* src = "multiplier_sc.sv:327.24-327.59" *) \copy2.finish_other  : \copy2.finish ;
  assign \copy2.a_reg_this  = \copy2.a_reg_same  ? (* src = "multiplier_sc.sv:328.38-328.70" *) \copy2.a_reg_other  : \copy2.a_reg ;
  assign \copy2.b_reg_this  = \copy2.b_reg_same  ? (* src = "multiplier_sc.sv:329.38-329.70" *) \copy2.b_reg_other  : \copy2.b_reg ;
  assign \copy2.counter_this  = \copy2.counter_same  ? (* src = "multiplier_sc.sv:330.31-330.69" *) \copy2.counter_other  : \copy2.counter ;
  assign \copy2.o_reg_this  = \copy2.o_reg_same  ? (* src = "multiplier_sc.sv:331.45-331.77" *) \copy2.o_reg_other  : \copy2.o_reg ;
  assign \copy2.busy_next  = \copy2.pause  ? (* src = "multiplier_sc.sv:361.22-361.93" *) \copy2.busy_this  : _040_;
  assign \copy2.finish_next  = \copy2.pause  ? (* src = "multiplier_sc.sv:362.24-362.103" *) \copy2.finish_this  : _038_;
  assign _042_ = _036_ ? (* src = "multiplier_sc.sv:363.59-363.98" *) \copy2.a  : \copy2.a_reg_this ;
  assign \copy2.a_reg_next  = \copy2.pause  ? (* src = "multiplier_sc.sv:363.38-363.98" *) \copy2.a_reg_this  : _042_;
  assign _043_ = _036_ ? (* src = "multiplier_sc.sv:364.59-364.103" *) \copy2.b  : 1'h0;
  assign \copy2.b_reg_next  = \copy2.pause  ? (* src = "multiplier_sc.sv:364.38-364.103" *) \copy2.b_reg_this  : _043_;
  assign _044_[0] = \copy2.busy_this  ? (* src = "multiplier_sc.sv:365.54-365.87" *) _030_ : 1'h0;
  assign \copy2.counter_next  = \copy2.pause  ? (* src = "multiplier_sc.sv:365.31-365.87" *) \copy2.counter_this  : _044_[0];
  assign _045_[1:0] = \copy2.b_reg_this  ? (* src = "multiplier_sc.sv:366.97-366.143" *) _032_[1:0] : 2'h0;
  assign _033_[1:0] = \copy2.busy_this  ? (* src = "multiplier_sc.sv:366.66-366.144" *) _031_ : 2'h0;
  assign \copy2.o_reg_next  = \copy2.pause  ? (* src = "multiplier_sc.sv:366.45-366.144" *) \copy2.o_reg_this  : _033_[1:0];
  assign _028_ = \copy2.finish_next_same  ? (* src = "multiplier_sc.sv:370.19-370.69" *) \copy2.finish_other_next  : \copy2.finish_next ;
  assign _026_ = \copy2.busy_next_same  ? (* src = "multiplier_sc.sv:371.17-371.61" *) \copy2.busy_other_next  : \copy2.busy_next ;
  assign _024_ = \copy2.a_reg_next_same  ? (* src = "multiplier_sc.sv:372.18-372.65" *) \copy2.a_reg_other_next  : \copy2.a_reg_next ;
  assign _025_ = \copy2.b_reg_next_same  ? (* src = "multiplier_sc.sv:373.18-373.65" *) \copy2.b_reg_other_next  : \copy2.b_reg_next ;
  assign _027_ = \copy2.counter_next_same  ? (* src = "multiplier_sc.sv:374.20-374.73" *) \copy2.counter_other_next  : \copy2.counter_next ;
  assign _029_ = \copy2.o_reg_next_same  ? (* src = "multiplier_sc.sv:375.18-375.65" *) \copy2.o_reg_other_next  : \copy2.o_reg_next ;
  assign _046_ = pause_1_reg && (* src = "multiplier_sc.sv:174.17-174.42" *) out_valid2;
  assign _047_ = pause_2_reg && (* src = "multiplier_sc.sv:174.46-174.71" *) out_valid1;
  assign _048_ = $signed(32'd1) && (* src = "multiplier_sc.sv:176.18-176.33" *) out_valid1;
  assign pause_1 = _048_ && (* src = "multiplier_sc.sv:176.18-176.48" *) _052_;
  assign _049_ = $signed(32'd1) && (* src = "multiplier_sc.sv:177.18-177.33" *) out_valid2;
  assign pause_2 = _049_ && (* src = "multiplier_sc.sv:177.18-177.48" *) _053_;
  assign _050_ = _054_ && (* src = "multiplier_sc.sv:207.23-207.46" *) out_valid1;
  assign _051_ = _050_ && (* src = "multiplier_sc.sv:207.23-207.60" *) out_valid2;
  assign _052_ = ! (* src = "multiplier_sc.sv:176.37-176.48" *) out_valid2;
  assign _053_ = ! (* src = "multiplier_sc.sv:177.37-177.48" *) out_valid1;
  assign _054_ = ! (* src = "multiplier_sc.sv:207.23-207.32" *) _001_;
  assign _055_ = ! (* src = "multiplier_sc.sv:244.36-244.44" *) drained;
  assign _056_ = all_pause || (* src = "multiplier_sc.sv:119.12-119.32" *) pause_1;
  assign _057_ = all_pause || (* src = "multiplier_sc.sv:164.12-164.32" *) pause_2;
  assign _000_ = _046_ || (* src = "multiplier_sc.sv:174.17-174.71" *) _047_;
  assign all_pause = _051_ || (* src = "multiplier_sc.sv:207.23-207.75" *) o_ever_diff;
  assign _058_ = all_pause || (* src = "multiplier_sc.sv:244.18-244.44" *) _055_;
  (* src = "multiplier_sc.sv:208.1-210.4" *)
  always @(posedge clk)
    o_ever_diff <= all_pause;
  (* src = "multiplier_sc.sv:171.1-175.4" *)
  always @(posedge clk)
    pause_1_reg <= pause_1;
  (* src = "multiplier_sc.sv:171.1-175.4" *)
  always @(posedge clk)
    pause_2_reg <= pause_2;
  (* src = "multiplier_sc.sv:171.1-175.4" *)
  always @(posedge clk)
    drained <= _000_;
  assign a_reg_diff_in = 1'h1;
  assign a_reg_next_same = 1'h0;
  assign assume_1_violate_in = 1'h0;
  assign assume_2_violate_in = 1'h0;
  assign assume_3_violate_in = all_pause;
  assign assume_predicate_violate_in = 1'h0;
  assign assume_violate = all_pause;
  assign b_reg_diff_in = 1'h1;
  assign b_reg_next_same = 1'h0;
  assign busy_diff_in = 1'h1;
  assign busy_next_same = 1'h0;
  assign counter_diff_in = 1'h1;
  assign counter_next_same = 1'h0;
  assign finish_diff_in = 1'h1;
  assign finish_next_same = 1'h0;
  assign o_ever_diff_in = all_pause;
  assign o_reg_diff_in = 1'h1;
  assign o_reg_next_same = 1'h0;
  assign _033_[31:2] = 30'hxxxxxxxx;
  assign _044_[31:1] = 31'b000000000000000000000000000000x;
  assign _045_[31:2] = 30'hxxxxxxxx;
  assign \copy2.o  = \copy2.o_reg_this ;
  assign \copy2.out_valid  = \copy2.finish_this ;
  assign \copy2.a  = a2;
  assign a_reg2 = \copy2.a_reg ;
  assign a_reg2_next = \copy2.a_reg_next ;
  assign \copy2.a_reg_next_same  = 1'h0;
  assign \copy2.a_reg_other  = a_reg1;
  assign \copy2.a_reg_other_next  = a_reg1_next;
  assign \copy2.a_reg_same  = 1'h0;
  assign \copy2.b  = b;
  assign b_reg2 = \copy2.b_reg ;
  assign b_reg2_next = \copy2.b_reg_next ;
  assign \copy2.b_reg_next_same  = 1'h0;
  assign \copy2.b_reg_other  = b_reg1;
  assign \copy2.b_reg_other_next  = b_reg1_next;
  assign \copy2.b_reg_same  = 1'h0;
  assign busy2 = \copy2.busy ;
  assign busy2_next = \copy2.busy_next ;
  assign \copy2.busy_next_same  = 1'h0;
  assign \copy2.busy_other  = busy1;
  assign \copy2.busy_other_next  = busy1_next;
  assign \copy2.busy_same  = 1'h0;
  assign \copy2.clk  = clk;
  assign counter2 = \copy2.counter ;
  assign counter2_next = \copy2.counter_next ;
  assign \copy2.counter_next_same  = 1'h0;
  assign \copy2.counter_other  = counter1;
  assign \copy2.counter_other_next  = counter1_next;
  assign \copy2.counter_same  = 1'h0;
  assign finish2 = \copy2.finish ;
  assign finish2_next = \copy2.finish_next ;
  assign \copy2.finish_next_same  = 1'h0;
  assign \copy2.finish_other  = finish1;
  assign \copy2.finish_other_next  = finish1_next;
  assign \copy2.finish_same  = 1'h0;
  assign \copy2.in_valid  = in_valid;
  assign o2 = \copy2.o ;
  assign o2_next = \copy2.o_reg_next ;
  assign \copy2.o_reg_next_same  = 1'h0;
  assign \copy2.o_reg_other  = o1;
  assign \copy2.o_reg_other_next  = o1_next;
  assign \copy2.o_reg_same  = 1'h0;
  assign out_valid2 = \copy2.out_valid ;
  assign \copy2.pause  = _057_;
  assign _011_[31:2] = 30'hxxxxxxxx;
  assign _022_[31:1] = 31'b000000000000000000000000000000x;
  assign _023_[31:2] = 30'hxxxxxxxx;
  assign \copy1.o  = \copy1.o_reg_this ;
  assign \copy1.out_valid  = \copy1.finish_this ;
  assign \copy1.a  = a1;
  assign a_reg1 = \copy1.a_reg ;
  assign a_reg1_next = \copy1.a_reg_next ;
  assign \copy1.a_reg_next_same  = 1'h0;
  assign \copy1.a_reg_same  = 1'h0;
  assign \copy1.b  = b;
  assign b_reg1 = \copy1.b_reg ;
  assign b_reg1_next = \copy1.b_reg_next ;
  assign \copy1.b_reg_next_same  = 1'h0;
  assign \copy1.b_reg_same  = 1'h0;
  assign busy1 = \copy1.busy ;
  assign busy1_next = \copy1.busy_next ;
  assign \copy1.busy_next_same  = 1'h0;
  assign \copy1.busy_same  = 1'h0;
  assign \copy1.clk  = clk;
  assign counter1 = \copy1.counter ;
  assign counter1_next = \copy1.counter_next ;
  assign \copy1.counter_next_same  = 1'h0;
  assign \copy1.counter_same  = 1'h0;
  assign finish1 = \copy1.finish ;
  assign finish1_next = \copy1.finish_next ;
  assign \copy1.finish_next_same  = 1'h0;
  assign \copy1.finish_same  = 1'h0;
  assign \copy1.in_valid  = in_valid;
  assign o1 = \copy1.o ;
  assign o1_next = \copy1.o_reg_next ;
  assign \copy1.o_reg_next_same  = 1'h0;
  assign \copy1.o_reg_same  = 1'h0;
  assign out_valid1 = \copy1.out_valid ;
  assign \copy1.pause  = _056_;
endmodule
