/* Generated by Yosys 0.40+50 (git sha1 0f9ee20ea, clang++ 15.0.0 -fPIC -Os) */

(* keep =  1  *)
(* top =  1  *)
(* src = "noninterference.sv:1.1-69.10" *)
module noninterference(clk, rst, a1, a2, b);
  (* src = "noninterference.sv:58.1-65.4" *)
  wire _00_;
  (* src = "noninterference.sv:67.18-67.24" *)
  wire _01_;
  (* src = "noninterference.sv:86.31-86.44" *)
  wire _02_;
  (* src = "noninterference.sv:83.13-83.17" *)
  wire _03_;
  (* src = "noninterference.sv:86.31-86.44" *)
  wire _04_;
  (* src = "noninterference.sv:83.13-83.17" *)
  wire _05_;
  (* src = "noninterference.sv:63.21-63.43" *)
  wire _06_;
  (* src = "noninterference.sv:67.18-67.48" *)
  wire _07_;
  (* src = "noninterference.sv:63.22-63.30" *)
  wire _08_;
  (* src = "noninterference.sv:4.11-4.13" *)
  input a1;
  wire a1;
  (* src = "noninterference.sv:5.11-5.13" *)
  input a2;
  wire a2;
  (* hdlname = "alu1 a" *)
  (* src = "noninterference.sv:74.11-74.12" *)
  wire \alu1.a ;
  (* hdlname = "alu1 a_in" *)
  (* src = "noninterference.sv:83.6-83.10" *)
  wire \alu1.a_in ;
  (* hdlname = "alu1 a_reg" *)
  (* src = "noninterference.sv:81.5-81.10" *)
  reg \alu1.a_reg  = 1'h0;
  (* hdlname = "alu1 b" *)
  (* src = "noninterference.sv:75.11-75.12" *)
  wire \alu1.b ;
  (* hdlname = "alu1 b_in" *)
  (* src = "noninterference.sv:84.6-84.10" *)
  wire \alu1.b_in ;
  (* hdlname = "alu1 b_reg" *)
  (* src = "noninterference.sv:82.5-82.10" *)
  reg \alu1.b_reg  = 1'h0;
  (* hdlname = "alu1 clk" *)
  (* src = "noninterference.sv:72.11-72.14" *)
  wire \alu1.clk ;
  (* hdlname = "alu1 o" *)
  (* src = "noninterference.sv:76.12-76.13" *)
  wire \alu1.o ;
  (* hdlname = "alu1 other_o" *)
  (* src = "noninterference.sv:78.11-78.18" *)
  wire \alu1.other_o ;
  (* hdlname = "alu1 rst" *)
  (* src = "noninterference.sv:73.11-73.14" *)
  wire \alu1.rst ;
  (* hdlname = "alu1 same_o" *)
  (* src = "noninterference.sv:77.11-77.17" *)
  wire \alu1.same_o ;
  (* hdlname = "alu2 a" *)
  (* src = "noninterference.sv:74.11-74.12" *)
  wire \alu2.a ;
  (* hdlname = "alu2 a_in" *)
  (* src = "noninterference.sv:83.6-83.10" *)
  wire \alu2.a_in ;
  (* hdlname = "alu2 a_reg" *)
  (* src = "noninterference.sv:81.5-81.10" *)
  reg \alu2.a_reg  = 1'h0;
  (* hdlname = "alu2 b" *)
  (* src = "noninterference.sv:75.11-75.12" *)
  wire \alu2.b ;
  (* hdlname = "alu2 b_in" *)
  (* src = "noninterference.sv:84.6-84.10" *)
  wire \alu2.b_in ;
  (* hdlname = "alu2 b_reg" *)
  (* src = "noninterference.sv:82.5-82.10" *)
  reg \alu2.b_reg  = 1'h0;
  (* hdlname = "alu2 clk" *)
  (* src = "noninterference.sv:72.11-72.14" *)
  wire \alu2.clk ;
  (* hdlname = "alu2 o" *)
  (* src = "noninterference.sv:76.12-76.13" *)
  wire \alu2.o ;
  (* hdlname = "alu2 other_o" *)
  (* src = "noninterference.sv:78.11-78.18" *)
  wire \alu2.other_o ;
  (* hdlname = "alu2 rst" *)
  (* src = "noninterference.sv:73.11-73.14" *)
  wire \alu2.rst ;
  (* hdlname = "alu2 same_o" *)
  (* src = "noninterference.sv:77.11-77.17" *)
  wire \alu2.same_o ;
  (* src = "noninterference.sv:57.5-57.13" *)
  reg assume_a = 1'h0;
  (* src = "noninterference.sv:6.11-6.12" *)
  input b;
  wire b;
  (* src = "noninterference.sv:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "noninterference.sv:9.6-9.8" *)
  wire o1;
  (* src = "noninterference.sv:9.10-9.12" *)
  wire o2;
  (* src = "noninterference.sv:3.11-3.14" *)
  input rst;
  wire rst;
  always @* if (1'h1) assert(_07_);
  assign _01_ = o1 == (* src = "noninterference.sv:67.18-67.24" *) o2;
  assign _02_ = \alu1.a_reg  & (* src = "noninterference.sv:86.31-86.44" *) \alu1.b_reg ;
  assign \alu1.a_in  = _03_ && (* src = "noninterference.sv:83.13-83.22" *) \alu1.a ;
  assign \alu1.b_in  = _03_ && (* src = "noninterference.sv:84.13-84.22" *) \alu1.b ;
  assign _03_ = ! (* src = "noninterference.sv:83.13-83.17" *) \alu1.rst ;
  (* src = "noninterference.sv:88.1-91.4" *)
  always @(posedge \alu1.clk )
    \alu1.a_reg  <= \alu1.a_in ;
  (* src = "noninterference.sv:88.1-91.4" *)
  always @(posedge \alu1.clk )
    \alu1.b_reg  <= \alu1.b_in ;
  assign \alu1.o  = \alu1.same_o  ? (* src = "noninterference.sv:86.12-86.44" *) \alu1.other_o  : _02_;
  assign _04_ = \alu2.a_reg  & (* src = "noninterference.sv:86.31-86.44" *) \alu2.b_reg ;
  assign \alu2.a_in  = _05_ && (* src = "noninterference.sv:83.13-83.22" *) \alu2.a ;
  assign \alu2.b_in  = _05_ && (* src = "noninterference.sv:84.13-84.22" *) \alu2.b ;
  assign _05_ = ! (* src = "noninterference.sv:83.13-83.17" *) \alu2.rst ;
  (* src = "noninterference.sv:88.1-91.4" *)
  always @(posedge \alu2.clk )
    \alu2.a_reg  <= \alu2.a_in ;
  (* src = "noninterference.sv:88.1-91.4" *)
  always @(posedge \alu2.clk )
    \alu2.b_reg  <= \alu2.b_in ;
  assign \alu2.o  = \alu2.same_o  ? (* src = "noninterference.sv:86.12-86.44" *) \alu2.other_o  : _04_;
  assign _06_ = _08_ || (* src = "noninterference.sv:63.21-63.43" *) assume_a;
  assign _07_ = _01_ || (* src = "noninterference.sv:67.18-67.48" *) _06_;
  assign _08_ = a1 != (* src = "noninterference.sv:63.22-63.30" *) a2;
  (* src = "noninterference.sv:58.1-65.4" *)
  always @(posedge clk)
    assume_a <= _00_;
  assign _00_ = rst ? (* full_case = 32'd1 *) (* src = "noninterference.sv:59.9-59.12|noninterference.sv:59.5-64.8" *) 1'h0 : _06_;
  assign \alu2.a  = a2;
  assign \alu2.b  = b;
  assign \alu2.clk  = clk;
  assign o2 = \alu2.o ;
  assign \alu2.other_o  = o1;
  assign \alu2.rst  = rst;
  assign \alu2.same_o  = 1'h0;
  assign \alu1.a  = a1;
  assign \alu1.b  = b;
  assign \alu1.clk  = clk;
  assign o1 = \alu1.o ;
  assign \alu1.other_o  = o2;
  assign \alu1.rst  = rst;
  assign \alu1.same_o  = 1'h0;
endmodule
