/* Generated by Yosys 0.40+50 (git sha1 0f9ee20ea, clang++ 15.0.0 -fPIC -Os) */

(* keep =  1  *)
(* top =  1  *)
(* src = "verilog/self_composition_multiplier.sv:5.1-41.10" *)
module top(clk, a1, a2, b, in_valid, o1, o2, out_valid1, out_valid2);
  (* src = "verilog/self_composition_multiplier.sv:38.18-38.26" *)
  wire _00_;
  (* src = "verilog/self_composition_multiplier.sv:38.30-38.36" *)
  wire _01_;
  (* src = "verilog/self_composition_multiplier.sv:39.18-39.42" *)
  wire _02_;
  wire [2:0] _03_;
  wire [7:0] _04_;
  (* src = "verilog/self_composition_multiplier.sv:73.77-73.93" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _05_;
  (* src = "verilog/self_composition_multiplier.sv:69.40-69.50" *)
  wire _06_;
  (* src = "verilog/self_composition_multiplier.sv:69.25-69.36" *)
  wire _07_;
  (* src = "verilog/self_composition_multiplier.sv:68.34-68.39" *)
  wire _08_;
  (* src = "verilog/self_composition_multiplier.sv:69.25-69.50" *)
  wire _09_;
  (* src = "verilog/self_composition_multiplier.sv:73.66-73.97" *)
  wire [31:0] _10_;
  wire [2:0] _11_;
  wire [7:0] _12_;
  (* src = "verilog/self_composition_multiplier.sv:73.77-73.93" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _13_;
  (* src = "verilog/self_composition_multiplier.sv:69.40-69.50" *)
  wire _14_;
  (* src = "verilog/self_composition_multiplier.sv:69.25-69.36" *)
  wire _15_;
  (* src = "verilog/self_composition_multiplier.sv:68.34-68.39" *)
  wire _16_;
  (* src = "verilog/self_composition_multiplier.sv:69.25-69.50" *)
  wire _17_;
  (* src = "verilog/self_composition_multiplier.sv:73.66-73.97" *)
  wire [31:0] _18_;
  (* src = "verilog/self_composition_multiplier.sv:38.18-38.36" *)
  wire _19_;
  (* src = "verilog/self_composition_multiplier.sv:7.26-7.28" *)
  input [3:0] a1;
  wire [3:0] a1;
  (* src = "verilog/self_composition_multiplier.sv:8.26-8.28" *)
  input [3:0] a2;
  wire [3:0] a2;
  (* src = "verilog/self_composition_multiplier.sv:9.26-9.27" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "verilog/self_composition_multiplier.sv:6.11-6.14" *)
  input clk;
  wire clk;
  (* hdlname = "copy1 a" *)
  (* src = "verilog/self_composition_multiplier.sv:48.26-48.27" *)
  wire [3:0] \copy1.a ;
  (* hdlname = "copy1 a_reg" *)
  (* src = "verilog/self_composition_multiplier.sv:53.24-53.29" *)
  reg [3:0] \copy1.a_reg  = 4'h0;
  (* hdlname = "copy1 a_reg_" *)
  (* src = "verilog/self_composition_multiplier.sv:69.25-69.31" *)
  wire \copy1.a_reg_ ;
  (* hdlname = "copy1 a_reg_next" *)
  (* src = "verilog/self_composition_multiplier.sv:70.25-70.35" *)
  wire [3:0] \copy1.a_reg_next ;
  (* hdlname = "copy1 b" *)
  (* src = "verilog/self_composition_multiplier.sv:49.26-49.27" *)
  wire [3:0] \copy1.b ;
  (* hdlname = "copy1 b_reg" *)
  (* src = "verilog/self_composition_multiplier.sv:53.31-53.36" *)
  reg [3:0] \copy1.b_reg  = 4'h0;
  (* hdlname = "copy1 b_reg_next" *)
  (* src = "verilog/self_composition_multiplier.sv:71.25-71.35" *)
  wire [3:0] \copy1.b_reg_next ;
  (* hdlname = "copy1 busy" *)
  (* src = "verilog/self_composition_multiplier.sv:55.9-55.13" *)
  reg \copy1.busy  = 1'h0;
  (* hdlname = "copy1 busy_next" *)
  (* src = "verilog/self_composition_multiplier.sv:68.10-68.19" *)
  wire \copy1.busy_next ;
  (* hdlname = "copy1 clk" *)
  (* src = "verilog/self_composition_multiplier.sv:46.11-46.14" *)
  wire \copy1.clk ;
  (* hdlname = "copy1 counter" *)
  (* src = "verilog/self_composition_multiplier.sv:57.15-57.22" *)
  reg [2:0] \copy1.counter ;
  (* hdlname = "copy1 counter_next" *)
  (* src = "verilog/self_composition_multiplier.sv:72.16-72.28" *)
  wire [2:0] \copy1.counter_next ;
  (* hdlname = "copy1 coutner" *)
  (* src = "verilog/self_composition_multiplier.sv:65.9-65.16" *)
  wire \copy1.coutner ;
  (* hdlname = "copy1 finish" *)
  (* src = "verilog/self_composition_multiplier.sv:56.9-56.15" *)
  reg \copy1.finish  = 1'h0;
  (* hdlname = "copy1 finish_next" *)
  (* src = "verilog/self_composition_multiplier.sv:69.10-69.21" *)
  wire \copy1.finish_next ;
  (* hdlname = "copy1 in_valid" *)
  (* src = "verilog/self_composition_multiplier.sv:47.11-47.19" *)
  wire \copy1.in_valid ;
  (* hdlname = "copy1 o" *)
  (* src = "verilog/self_composition_multiplier.sv:50.34-50.35" *)
  wire [7:0] \copy1.o ;
  (* hdlname = "copy1 o_reg" *)
  (* src = "verilog/self_composition_multiplier.sv:54.31-54.36" *)
  reg [7:0] \copy1.o_reg  = 8'h00;
  (* hdlname = "copy1 o_reg_next" *)
  (* src = "verilog/self_composition_multiplier.sv:73.32-73.42" *)
  wire [7:0] \copy1.o_reg_next ;
  (* hdlname = "copy1 out_valid" *)
  (* src = "verilog/self_composition_multiplier.sv:51.12-51.21" *)
  wire \copy1.out_valid ;
  (* hdlname = "copy2 a" *)
  (* src = "verilog/self_composition_multiplier.sv:48.26-48.27" *)
  wire [3:0] \copy2.a ;
  (* hdlname = "copy2 a_reg" *)
  (* src = "verilog/self_composition_multiplier.sv:53.24-53.29" *)
  reg [3:0] \copy2.a_reg  = 4'h0;
  (* hdlname = "copy2 a_reg_" *)
  (* src = "verilog/self_composition_multiplier.sv:69.25-69.31" *)
  wire \copy2.a_reg_ ;
  (* hdlname = "copy2 a_reg_next" *)
  (* src = "verilog/self_composition_multiplier.sv:70.25-70.35" *)
  wire [3:0] \copy2.a_reg_next ;
  (* hdlname = "copy2 b" *)
  (* src = "verilog/self_composition_multiplier.sv:49.26-49.27" *)
  wire [3:0] \copy2.b ;
  (* hdlname = "copy2 b_reg" *)
  (* src = "verilog/self_composition_multiplier.sv:53.31-53.36" *)
  reg [3:0] \copy2.b_reg  = 4'h0;
  (* hdlname = "copy2 b_reg_next" *)
  (* src = "verilog/self_composition_multiplier.sv:71.25-71.35" *)
  wire [3:0] \copy2.b_reg_next ;
  (* hdlname = "copy2 busy" *)
  (* src = "verilog/self_composition_multiplier.sv:55.9-55.13" *)
  reg \copy2.busy  = 1'h0;
  (* hdlname = "copy2 busy_next" *)
  (* src = "verilog/self_composition_multiplier.sv:68.10-68.19" *)
  wire \copy2.busy_next ;
  (* hdlname = "copy2 clk" *)
  (* src = "verilog/self_composition_multiplier.sv:46.11-46.14" *)
  wire \copy2.clk ;
  (* hdlname = "copy2 counter" *)
  (* src = "verilog/self_composition_multiplier.sv:57.15-57.22" *)
  reg [2:0] \copy2.counter ;
  (* hdlname = "copy2 counter_next" *)
  (* src = "verilog/self_composition_multiplier.sv:72.16-72.28" *)
  wire [2:0] \copy2.counter_next ;
  (* hdlname = "copy2 coutner" *)
  (* src = "verilog/self_composition_multiplier.sv:65.9-65.16" *)
  wire \copy2.coutner ;
  (* hdlname = "copy2 finish" *)
  (* src = "verilog/self_composition_multiplier.sv:56.9-56.15" *)
  reg \copy2.finish  = 1'h0;
  (* hdlname = "copy2 finish_next" *)
  (* src = "verilog/self_composition_multiplier.sv:69.10-69.21" *)
  wire \copy2.finish_next ;
  (* hdlname = "copy2 in_valid" *)
  (* src = "verilog/self_composition_multiplier.sv:47.11-47.19" *)
  wire \copy2.in_valid ;
  (* hdlname = "copy2 o" *)
  (* src = "verilog/self_composition_multiplier.sv:50.34-50.35" *)
  wire [7:0] \copy2.o ;
  (* hdlname = "copy2 o_reg" *)
  (* src = "verilog/self_composition_multiplier.sv:54.31-54.36" *)
  reg [7:0] \copy2.o_reg  = 8'h00;
  (* hdlname = "copy2 o_reg_next" *)
  (* src = "verilog/self_composition_multiplier.sv:73.32-73.42" *)
  wire [7:0] \copy2.o_reg_next ;
  (* hdlname = "copy2 out_valid" *)
  (* src = "verilog/self_composition_multiplier.sv:51.12-51.21" *)
  wire \copy2.out_valid ;
  (* src = "verilog/self_composition_multiplier.sv:10.11-10.19" *)
  input in_valid;
  wire in_valid;
  (* src = "verilog/self_composition_multiplier.sv:11.34-11.36" *)
  output [7:0] o1;
  wire [7:0] o1;
  (* src = "verilog/self_composition_multiplier.sv:12.34-12.36" *)
  output [7:0] o2;
  wire [7:0] o2;
  (* src = "verilog/self_composition_multiplier.sv:13.12-13.22" *)
  output out_valid1;
  wire out_valid1;
  (* src = "verilog/self_composition_multiplier.sv:14.12-14.22" *)
  output out_valid2;
  wire out_valid2;
  always @* if (1'h1) assert(_02_);
  always @* if (1'h1) assume(_19_);
  assign _00_ = a1 == (* src = "verilog/self_composition_multiplier.sv:38.18-38.26" *) a2;
  assign _01_ = ! (* src = "verilog/self_composition_multiplier.sv:38.30-38.36" *) b;
  assign _02_ = out_valid1 == (* src = "verilog/self_composition_multiplier.sv:39.18-39.42" *) out_valid2;
  assign _03_ = \copy1.counter  + (* src = "verilog/self_composition_multiplier.sv:72.43-72.54" *) 1'h1;
  assign _04_ = \copy1.o_reg  + (* src = "verilog/self_composition_multiplier.sv:73.57-73.98" *) _10_[7:0];
  assign _06_ = ! (* src = "verilog/self_composition_multiplier.sv:69.40-69.50" *) \copy1.b_reg ;
  assign _07_ = ~ (* src = "verilog/self_composition_multiplier.sv:69.25-69.36" *) \copy1.a_reg_ ;
  assign \copy1.busy_next  = \copy1.in_valid  && (* src = "verilog/self_composition_multiplier.sv:68.22-68.39" *) _08_;
  assign \copy1.finish_next  = _09_ && (* src = "verilog/self_composition_multiplier.sv:69.24-69.59" *) \copy1.busy ;
  assign _08_ = ! (* src = "verilog/self_composition_multiplier.sv:68.34-68.39" *) \copy1.busy ;
  assign _09_ = _07_ || (* src = "verilog/self_composition_multiplier.sv:69.25-69.50" *) _06_;
  (* src = "verilog/self_composition_multiplier.sv:75.5-82.8" *)
  always @(posedge \copy1.clk )
    \copy1.a_reg  <= \copy1.a_reg_next ;
  (* src = "verilog/self_composition_multiplier.sv:75.5-82.8" *)
  always @(posedge \copy1.clk )
    \copy1.b_reg  <= \copy1.b_reg_next ;
  (* src = "verilog/self_composition_multiplier.sv:75.5-82.8" *)
  always @(posedge \copy1.clk )
    \copy1.o_reg  <= \copy1.o_reg_next ;
  (* src = "verilog/self_composition_multiplier.sv:75.5-82.8" *)
  always @(posedge \copy1.clk )
    \copy1.busy  <= \copy1.busy_next ;
  (* src = "verilog/self_composition_multiplier.sv:75.5-82.8" *)
  always @(posedge \copy1.clk )
    \copy1.finish  <= \copy1.finish_next ;
  (* src = "verilog/self_composition_multiplier.sv:75.5-82.8" *)
  always @(posedge \copy1.clk )
    \copy1.counter  <= \copy1.counter_next ;
  assign _05_[7:0] = \copy1.a_reg  << (* src = "verilog/self_composition_multiplier.sv:73.77-73.93" *) \copy1.counter ;
  assign \copy1.a_reg_next  = \copy1.busy_next  ? (* src = "verilog/self_composition_multiplier.sv:70.38-70.67" *) \copy1.a  : \copy1.a_reg ;
  assign \copy1.b_reg_next  = \copy1.busy_next  ? (* src = "verilog/self_composition_multiplier.sv:71.38-71.72" *) \copy1.b  : { 1'h0, \copy1.b_reg [3:1] };
  assign \copy1.counter_next  = \copy1.busy  ? (* src = "verilog/self_composition_multiplier.sv:72.31-72.54" *) _03_ : 3'h0;
  assign _10_[7:0] = \copy1.b_reg [0] ? (* src = "verilog/self_composition_multiplier.sv:73.66-73.97" *) _05_[7:0] : 8'h00;
  assign \copy1.o_reg_next  = \copy1.busy  ? (* src = "verilog/self_composition_multiplier.sv:73.45-73.98" *) _04_ : 8'h00;
  assign _11_ = \copy2.counter  + (* src = "verilog/self_composition_multiplier.sv:72.43-72.54" *) 1'h1;
  assign _12_ = \copy2.o_reg  + (* src = "verilog/self_composition_multiplier.sv:73.57-73.98" *) _18_[7:0];
  assign _14_ = ! (* src = "verilog/self_composition_multiplier.sv:69.40-69.50" *) \copy2.b_reg ;
  assign _15_ = ~ (* src = "verilog/self_composition_multiplier.sv:69.25-69.36" *) \copy2.a_reg_ ;
  assign \copy2.busy_next  = \copy2.in_valid  && (* src = "verilog/self_composition_multiplier.sv:68.22-68.39" *) _16_;
  assign \copy2.finish_next  = _17_ && (* src = "verilog/self_composition_multiplier.sv:69.24-69.59" *) \copy2.busy ;
  assign _16_ = ! (* src = "verilog/self_composition_multiplier.sv:68.34-68.39" *) \copy2.busy ;
  assign _17_ = _15_ || (* src = "verilog/self_composition_multiplier.sv:69.25-69.50" *) _14_;
  (* src = "verilog/self_composition_multiplier.sv:75.5-82.8" *)
  always @(posedge \copy2.clk )
    \copy2.a_reg  <= \copy2.a_reg_next ;
  (* src = "verilog/self_composition_multiplier.sv:75.5-82.8" *)
  always @(posedge \copy2.clk )
    \copy2.b_reg  <= \copy2.b_reg_next ;
  (* src = "verilog/self_composition_multiplier.sv:75.5-82.8" *)
  always @(posedge \copy2.clk )
    \copy2.o_reg  <= \copy2.o_reg_next ;
  (* src = "verilog/self_composition_multiplier.sv:75.5-82.8" *)
  always @(posedge \copy2.clk )
    \copy2.busy  <= \copy2.busy_next ;
  (* src = "verilog/self_composition_multiplier.sv:75.5-82.8" *)
  always @(posedge \copy2.clk )
    \copy2.finish  <= \copy2.finish_next ;
  (* src = "verilog/self_composition_multiplier.sv:75.5-82.8" *)
  always @(posedge \copy2.clk )
    \copy2.counter  <= \copy2.counter_next ;
  assign _13_[7:0] = \copy2.a_reg  << (* src = "verilog/self_composition_multiplier.sv:73.77-73.93" *) \copy2.counter ;
  assign \copy2.a_reg_next  = \copy2.busy_next  ? (* src = "verilog/self_composition_multiplier.sv:70.38-70.67" *) \copy2.a  : \copy2.a_reg ;
  assign \copy2.b_reg_next  = \copy2.busy_next  ? (* src = "verilog/self_composition_multiplier.sv:71.38-71.72" *) \copy2.b  : { 1'h0, \copy2.b_reg [3:1] };
  assign \copy2.counter_next  = \copy2.busy  ? (* src = "verilog/self_composition_multiplier.sv:72.31-72.54" *) _11_ : 3'h0;
  assign _18_[7:0] = \copy2.b_reg [0] ? (* src = "verilog/self_composition_multiplier.sv:73.66-73.97" *) _13_[7:0] : 8'h00;
  assign \copy2.o_reg_next  = \copy2.busy  ? (* src = "verilog/self_composition_multiplier.sv:73.45-73.98" *) _12_ : 8'h00;
  assign _19_ = _00_ || (* src = "verilog/self_composition_multiplier.sv:38.18-38.36" *) _01_;
  assign _18_[31:8] = 24'hxxxxxx;
  assign \copy2.coutner  = 1'h0;
  assign \copy2.o  = \copy2.o_reg ;
  assign \copy2.out_valid  = \copy2.finish ;
  assign \copy2.a  = a2;
  assign \copy2.b  = b;
  assign \copy2.clk  = clk;
  assign \copy2.in_valid  = in_valid;
  assign o2 = \copy2.o ;
  assign out_valid2 = \copy2.out_valid ;
  assign _10_[31:8] = 24'hxxxxxx;
  assign \copy1.coutner  = 1'h0;
  assign \copy1.o  = \copy1.o_reg ;
  assign \copy1.out_valid  = \copy1.finish ;
  assign \copy1.a  = a1;
  assign \copy1.b  = b;
  assign \copy1.clk  = clk;
  assign \copy1.in_valid  = in_valid;
  assign o1 = \copy1.o ;
  assign out_valid1 = \copy1.out_valid ;
endmodule
